/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package continentalconquest;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author x13332576
 */
public class AdminGUI extends javax.swing.JFrame {
    String question;
    String country;
    String correctA;
    String wrongA;
    String wrongA2;
    String wrongA3;
    String insert;
    
    /**
     * Creates new form AdminGUI
     */
    public AdminGUI() throws MalformedURLException {
        initComponents();
        question= "";
        country="";
        correctA="";
        wrongA="";
        wrongA2="";
        wrongA3="";
        // CustomCursor();
      
    }
 public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        QuestionLbl = new javax.swing.JLabel();
        CountryLbl = new javax.swing.JLabel();
        CaLbl = new javax.swing.JLabel();
        Wa1Lbl = new javax.swing.JLabel();
        Wa2Lbl = new javax.swing.JLabel();
        Wa3Lbl = new javax.swing.JLabel();
        questTF = new javax.swing.JTextField();
        countryTF = new javax.swing.JTextField();
        CorrectaTF = new javax.swing.JTextField();
        WrongTF1 = new javax.swing.JTextField();
        WrongTF2 = new javax.swing.JTextField();
        WrongTF3 = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Add a new question:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(249, 71, 162, 50);

        QuestionLbl.setText("Question:");
        getContentPane().add(QuestionLbl);
        QuestionLbl.setBounds(128, 142, 64, 14);

        CountryLbl.setText("Country:");
        getContentPane().add(CountryLbl);
        CountryLbl.setBounds(128, 180, 64, 14);

        CaLbl.setText("Correct Answer:");
        getContentPane().add(CaLbl);
        CaLbl.setBounds(128, 218, 79, 14);

        Wa1Lbl.setText("Wrong Answer:");
        getContentPane().add(Wa1Lbl);
        Wa1Lbl.setBounds(128, 256, 75, 14);

        Wa2Lbl.setText("Wrong Answer:");
        getContentPane().add(Wa2Lbl);
        Wa2Lbl.setBounds(128, 294, 75, 14);

        Wa3Lbl.setText("Wrong Answer:");
        getContentPane().add(Wa3Lbl);
        Wa3Lbl.setBounds(128, 329, 75, 14);
        getContentPane().add(questTF);
        questTF.setBounds(211, 139, 255, 20);
        getContentPane().add(countryTF);
        countryTF.setBounds(211, 177, 255, 20);
        getContentPane().add(CorrectaTF);
        CorrectaTF.setBounds(211, 215, 255, 20);
        getContentPane().add(WrongTF1);
        WrongTF1.setBounds(211, 253, 255, 20);
        getContentPane().add(WrongTF2);
        WrongTF2.setBounds(211, 291, 255, 20);
        getContentPane().add(WrongTF3);
        WrongTF3.setBounds(213, 329, 253, 20);

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddBtn);
        AddBtn.setBounds(250, 389, 147, 56);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(10, 30, 88, 35);
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        StartGUI newGUI = null;
        try {
            newGUI = new StartGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        newGUI.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        question = questTF.getText();
        country = countryTF.getText();
        correctA = CorrectaTF.getText();
        wrongA = WrongTF1.getText();
        wrongA2 = WrongTF2.getText();
        wrongA3= WrongTF3.getText();
        
        //avatar = selectionGroup.getSelection();

             try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            insert = "insert into Question values('"+question+"','"+country+"','"+correctA+"','"+wrongA+"','"+wrongA2+"','"+wrongA3+"','N')";
            st.executeUpdate(insert);
            /* */
            JOptionPane.showMessageDialog(null,"Success!");
             

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        
        
    }//GEN-LAST:event_AddBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AdminGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CaLbl;
    private javax.swing.JLabel CloseB;
    private javax.swing.JTextField CorrectaTF;
    private javax.swing.JLabel CountryLbl;
    private javax.swing.JLabel MinB;
    private javax.swing.JLabel QuestionLbl;
    private javax.swing.JLabel Wa1Lbl;
    private javax.swing.JLabel Wa2Lbl;
    private javax.swing.JLabel Wa3Lbl;
    private javax.swing.JTextField WrongTF1;
    private javax.swing.JTextField WrongTF2;
    private javax.swing.JTextField WrongTF3;
    private javax.swing.JTextField countryTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField questTF;
    // End of variables declaration//GEN-END:variables
}
