/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13360866
 */
public class AlgeriaQuizGUI extends javax.swing.JFrame {
    jdbcTest t;
    String insert;
    String question;
    int count;
    int count2;
    private static final String VOICENAME = "kevin16";
    /**
     * Creates new form AlgeriaQuizGUI
     */
    public AlgeriaQuizGUI() {
        initComponents();
        t = new jdbcTest();
        question = "";
        count=0;
        count2 = 0;
       
         try {
            
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";     
            ResultSet rs = st.executeQuery(find);
        
                /* https://www.youtube.com/watch?v=MY4FavUyFNQ */  
            
            while(rs.next()){
                question = AlgeriaQuestionlbl.getText();
                AlgeriaQuestionlbl.setText("\n"+rs.getString("quest")); 
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");
  
                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
             
                 
                String [] arr = solutionArray;
                Random rgen = new Random();
                 int N = arr.length;
                 /*
                  * fisher yates shuffle
                  *
                  * 9/3/2015
                  *
                  * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                  * @author sean trant 13332576
                  */ 
                
                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;
                    
                    
                    AlgeriaAns1.setText(arr[0]);
                    AlgeriaAns2.setText(arr[1]);
                    AlgeriaAns3.setText(arr[2]);
                    AlgeriaAns4.setText(arr[3]); 
                }

            }
            
       
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }            
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        voiceBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        Algerialbl = new javax.swing.JLabel();
        AlgeriaQuestionlbl = new javax.swing.JLabel();
        ExitQuiz = new javax.swing.JButton();
        Scorelbl = new javax.swing.JLabel();
        AlgeriaAns1 = new javax.swing.JButton();
        AlgeriaAns2 = new javax.swing.JButton();
        AlgeriaAns3 = new javax.swing.JButton();
        AlgeriaAns4 = new javax.swing.JButton();
        FlagImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 100, 620, 2);

        voiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/voice button.png"))); // NOI18N
        voiceBtn.setContentAreaFilled(false);
        voiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voiceBtn);
        voiceBtn.setBounds(520, 10, 80, 70);

        yBtn.setBackground(new java.awt.Color(255, 255, 255));
        yBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        yBtn.setText("Yes");
        yBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        yBtn.setContentAreaFilled(false);
        yBtn.setOpaque(true);
        yBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yBtnActionPerformed(evt);
            }
        });
        getContentPane().add(yBtn);
        yBtn.setBounds(110, 300, 210, 70);

        nBtn.setBackground(new java.awt.Color(255, 255, 255));
        nBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nBtn.setText("No");
        nBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nBtn.setContentAreaFilled(false);
        nBtn.setOpaque(true);
        nBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nBtn);
        nBtn.setBounds(340, 300, 210, 70);

        Algerialbl.setFont(new java.awt.Font("Old English Text MT", 3, 36)); // NOI18N
        Algerialbl.setForeground(new java.awt.Color(0, 0, 255));
        Algerialbl.setText("Algeria");
        getContentPane().add(Algerialbl);
        Algerialbl.setBounds(10, 10, 250, 60);

        AlgeriaQuestionlbl.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        getContentPane().add(AlgeriaQuestionlbl);
        AlgeriaQuestionlbl.setBounds(20, 200, 570, 30);

        ExitQuiz.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        ExitQuiz.setForeground(new java.awt.Color(0, 0, 255));
        ExitQuiz.setText("Retire Quest");
        ExitQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitQuizActionPerformed(evt);
            }
        });
        getContentPane().add(ExitQuiz);
        ExitQuiz.setBounds(10, 500, 140, 30);

        Scorelbl.setFont(new java.awt.Font("Old English Text MT", 3, 24)); // NOI18N
        Scorelbl.setForeground(new java.awt.Color(0, 0, 255));
        getContentPane().add(Scorelbl);
        Scorelbl.setBounds(200, 490, 390, 40);

        AlgeriaAns1.setFont(new java.awt.Font("Old English Text MT", 0, 14)); // NOI18N
        AlgeriaAns1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AlgeriaAns1.setContentAreaFilled(false);
        AlgeriaAns1.setOpaque(true);
        AlgeriaAns1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AlgeriaAns1MousePressed(evt);
            }
        });
        AlgeriaAns1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgeriaAns1ActionPerformed(evt);
            }
        });
        getContentPane().add(AlgeriaAns1);
        AlgeriaAns1.setBounds(110, 270, 150, 50);

        AlgeriaAns2.setFont(new java.awt.Font("Old English Text MT", 0, 14)); // NOI18N
        AlgeriaAns2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AlgeriaAns2.setContentAreaFilled(false);
        AlgeriaAns2.setOpaque(true);
        AlgeriaAns2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgeriaAns2ActionPerformed(evt);
            }
        });
        getContentPane().add(AlgeriaAns2);
        AlgeriaAns2.setBounds(400, 270, 150, 50);

        AlgeriaAns3.setFont(new java.awt.Font("Old English Text MT", 0, 14)); // NOI18N
        AlgeriaAns3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AlgeriaAns3.setContentAreaFilled(false);
        AlgeriaAns3.setOpaque(true);
        AlgeriaAns3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgeriaAns3ActionPerformed(evt);
            }
        });
        getContentPane().add(AlgeriaAns3);
        AlgeriaAns3.setBounds(110, 360, 150, 50);

        AlgeriaAns4.setFont(new java.awt.Font("Old English Text MT", 0, 14)); // NOI18N
        AlgeriaAns4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        AlgeriaAns4.setContentAreaFilled(false);
        AlgeriaAns4.setOpaque(true);
        AlgeriaAns4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgeriaAns4ActionPerformed(evt);
            }
        });
        getContentPane().add(AlgeriaAns4);
        AlgeriaAns4.setBounds(400, 360, 150, 50);

        FlagImage.setBackground(new java.awt.Color(255, 255, 255));
        FlagImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Algeria.jpg"))); // NOI18N
        getContentPane().add(FlagImage);
        FlagImage.setBounds(0, 0, 620, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlgeriaAns2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgeriaAns2ActionPerformed
        // TODO add your handling code here:
      if(count2==10){
                    Scorelbl.setVisible(true);
                    AlgeriaAns1.setVisible(false);
                    AlgeriaAns2.setVisible(false);
                    AlgeriaAns3.setVisible(false);
                    AlgeriaAns4.setVisible(false);
                    if(count<10){
                        Algerialbl.setText("Retreat!");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        Algerialbl.setText("Algeria conquered");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
         try {
             
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";     
            ResultSet rs = st.executeQuery(find);
        
           /* https://www.youtube.com/watch?v=MY4FavUyFNQ */  
            
            while(rs.next()){
                question = AlgeriaQuestionlbl.getText();
                AlgeriaQuestionlbl.setText("\n"+rs.getString("quest")); 
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
 
                String [] arr = solutionArray;
                Random rgen = new Random();
                 int N = arr.length;
                 /*
                  * fisher yates shuffle
                  *
                  * 9/3/2015
                  *
                  * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                  * @author sean trant 13332576
                  */ 
                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;
  
                    AlgeriaAns1.setText(arr[0]);
                    AlgeriaAns2.setText(arr[1]);
                    AlgeriaAns3.setText(arr[2]);
                    AlgeriaAns4.setText(arr[3]); 
                }
                
              if(arr[1].equals(rs.getString("answer"))){
                    Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    Scorelbl.setText("Your last answer was correct!");
                    } 
                 else{
                     Scorelbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
                 
        
        
    }//GEN-LAST:event_AlgeriaAns2ActionPerformed

    private void AlgeriaAns1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgeriaAns1ActionPerformed
        // TODO add your handling code here:
        // String country;
        //country =  AlgeriaQuestionlbl.getText();
       if(count2==10){
                    Scorelbl.setVisible(true);
                    AlgeriaAns1.setVisible(false);
                    AlgeriaAns2.setVisible(false);
                    AlgeriaAns3.setVisible(false);
                    AlgeriaAns4.setVisible(false);
                    if(count<10){
                        Algerialbl.setText("Retreat!");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        Algerialbl.setText("Algeria conquered");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
         try {
             
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";     
            ResultSet rs = st.executeQuery(find);
        
           /* https://www.youtube.com/watch?v=MY4FavUyFNQ */  
            
            while(rs.next()){
                question = AlgeriaQuestionlbl.getText();
                AlgeriaQuestionlbl.setText("\n"+rs.getString("quest")); 
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
 
                String [] arr = solutionArray;
                Random rgen = new Random();
                 int N = arr.length;
                 /*
                  * fisher yates shuffle
                  *
                  * 9/3/2015
                  *
                  * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                  * @author sean trant 13332576
                  */ 
                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;
  
                    AlgeriaAns1.setText(arr[0]);
                    AlgeriaAns2.setText(arr[1]);
                    AlgeriaAns3.setText(arr[2]);
                    AlgeriaAns4.setText(arr[3]); 
                      
                }
               if(arr[0].equals(rs.getString("answer"))){
                    Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    Scorelbl.setText("Your last answer was correct!");
                    } 
                 else{
                     Scorelbl.setText("AHH, your last answer was incorrect.");
                 } 
           
            }
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
         
    }//GEN-LAST:event_AlgeriaAns1ActionPerformed

    private void ExitQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitQuizActionPerformed
        // TODO add your handling code here:
           AfricaQuizGUI newGUI = new AfricaQuizGUI();
        newGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ExitQuizActionPerformed

    private void AlgeriaAns1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlgeriaAns1MousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_AlgeriaAns1MousePressed

    private void AlgeriaAns3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgeriaAns3ActionPerformed
        // TODO add your handling code here:
      if(count2==10){
                    Scorelbl.setVisible(true);
                    AlgeriaAns1.setVisible(false);
                    AlgeriaAns2.setVisible(false);
                    AlgeriaAns3.setVisible(false);
                    AlgeriaAns4.setVisible(false);
                    if(count<10){
                        Algerialbl.setText("Retreat!");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        Algerialbl.setText("Algeria conquered");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
         try {
             
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";     
            ResultSet rs = st.executeQuery(find);
        
           /* https://www.youtube.com/watch?v=MY4FavUyFNQ */  
            
            while(rs.next()){
                question = AlgeriaQuestionlbl.getText();
                AlgeriaQuestionlbl.setText("\n"+rs.getString("quest")); 
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
 
                String [] arr = solutionArray;
                Random rgen = new Random();
                 int N = arr.length;
                 /*
                  * fisher yates shuffle
                  * 9/3/2015
                  * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                  * @author sean trant 13332576
                  */ 
                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;
  
                    AlgeriaAns1.setText(arr[0]);
                    AlgeriaAns2.setText(arr[1]);
                    AlgeriaAns3.setText(arr[2]);
                    AlgeriaAns4.setText(arr[3]); 
                }
                
                if(arr[2].equals(rs.getString("answer"))){
                       Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    Scorelbl.setText("Your last answer was correct!");
                    } 
                 else{
                     Scorelbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
                 
        
    }//GEN-LAST:event_AlgeriaAns3ActionPerformed

    private void AlgeriaAns4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgeriaAns4ActionPerformed
        // TODO add your handling code here:
      if(count2==10){
                    Scorelbl.setVisible(true);
                    AlgeriaAns1.setVisible(false);
                    AlgeriaAns2.setVisible(false);
                    AlgeriaAns3.setVisible(false);
                    AlgeriaAns4.setVisible(false);
                    if(count<10){
                        Algerialbl.setText("Retreat!");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        Algerialbl.setText("Algeria conquered");
                        AlgeriaQuestionlbl.setText("");
                        Scorelbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
         try {
             
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";     
            ResultSet rs = st.executeQuery(find);
        
           /* https://www.youtube.com/watch?v=MY4FavUyFNQ */  
            
            while(rs.next()){
                question = AlgeriaQuestionlbl.getText();
                AlgeriaQuestionlbl.setText("\n"+rs.getString("quest")); 
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
 
                String [] arr = solutionArray;
                Random rgen = new Random();
                 int N = arr.length;
                 /*
                  * fisher yates shuffle
                  *
                  * 9/3/2015
                  *
                  * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                  * @author sean trant 13332576
                  */ 
                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;
  
                    AlgeriaAns1.setText(arr[0]);
                    AlgeriaAns2.setText(arr[1]);
                    AlgeriaAns3.setText(arr[2]);
                    AlgeriaAns4.setText(arr[3]); 
                }
                
                if(arr[3].equals(rs.getString("answer"))){
                     Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    Scorelbl.setText("Your last answer was correct!");
                    } 
                 else{
                     Scorelbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
    }//GEN-LAST:event_AlgeriaAns4ActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);

            Statement st = (Statement) conn.createStatement();

            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Question set q_sel = 'N';";
            st.executeUpdate(update);
            /* */
            try {
                Algerialbl.setText("Algeria Quiz");
                AlgeriaAns1.setVisible(true);
                AlgeriaAns2.setVisible(true);
                AlgeriaAns3.setVisible(true);
                AlgeriaAns4.setVisible(true);
                count2=0;
                count=0;
                AlgeriaQuestionlbl.setVisible(true);
                Scorelbl.setVisible(false);
                yBtn.setVisible(false);
                nBtn.setVisible(false);
                String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'algeria' and q_sel = 'N' order by rand() limit 1;";
                ResultSet rs = st.executeQuery(find);

                /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

                while(rs.next()){
                    question = AlgeriaQuestionlbl.getText();
                    AlgeriaQuestionlbl.setText("\n"+rs.getString("quest"));
                    Statement st2 = conn.createStatement();
                    st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                    String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
                    String [] arr = solutionArray;
                    arr = solutionArray;
                    Random rgen = new Random();
                    int N = arr.length;
                    /*
                    * fisher yates shuffle
                    *
                    * 9/3/2015
                    *
                    * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                    * @author sean trant 13332576
                    */

                    for (int i = 0; i < N; i++) {
                        // choose index uniformly in [i, N-1]
                        int r = i + (int) (Math.random() * (N - i));
                        Object swap = arr[r];
                        arr[r] = arr[i];
                        arr[i] = (String)swap;

                        AlgeriaAns1.setText(arr[0]);
                        AlgeriaAns2.setText(arr[1]);
                        AlgeriaAns3.setText(arr[2]);
                        AlgeriaAns4.setText(arr[3]);
                    }

                }

            } catch (Exception ex) {
                System.out.println("AGGHHHH!!!!!");
            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }
    }//GEN-LAST:event_yBtnActionPerformed

    private void nBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBtnActionPerformed
        // TODO add your handling code here:
        EuropeGUI europe =null;
        try {
            europe = new EuropeGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(AlgeriaQuizGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        europe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nBtnActionPerformed

    private void voiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceBtnActionPerformed
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        voice.allocate();
        try{
            voice.speak(AlgeriaQuestionlbl.getText());
            voice.speak("Answer, one");
            voice.speak(AlgeriaAns1.getText());
            voice.speak("Answer, two");
            voice.speak(AlgeriaAns2.getText());
            voice.speak("Answer, three");
            voice.speak(AlgeriaAns3.getText());
            voice.speak("Answer, four");
            voice.speak(AlgeriaAns4.getText());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_voiceBtnActionPerformed
     

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgeriaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgeriaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgeriaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgeriaQuizGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgeriaQuizGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlgeriaAns1;
    private javax.swing.JButton AlgeriaAns2;
    private javax.swing.JButton AlgeriaAns3;
    private javax.swing.JButton AlgeriaAns4;
    private javax.swing.JLabel AlgeriaQuestionlbl;
    private javax.swing.JLabel Algerialbl;
    private javax.swing.JButton ExitQuiz;
    private javax.swing.JLabel FlagImage;
    private javax.swing.JLabel Scorelbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton nBtn;
    private javax.swing.JButton voiceBtn;
    private javax.swing.JButton yBtn;
    // End of variables declaration//GEN-END:variables
}
