/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author x13508623
 */
public class AmericanTutorialGUI extends javax.swing.JFrame {
private String[] arr;
int score;

    /**
     * Creates new form AmericanTutorialGUI
     */
    public AmericanTutorialGUI() {
        initComponents();
        backBtn.setVisible(false);
        BrazilTA.setVisible(false);
        nextBtn.setVisible(false);
        BrazilLbl.setVisible(false);
        CanadaLbl.setVisible(false);
        USALbl.setVisible(false);
        PeruLbl.setVisible(false);
        USATA.setVisible(false);
        PeruTA.setVisible(false);
        CanadaTA.setVisible(false);
        noticeTA.setVisible(false);
        reminderLbl.setVisible(false);
        score = 0;
        scoreLbl.setText(String.valueOf(score));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        PeruLbl = new javax.swing.JLabel();
        USALbl = new javax.swing.JLabel();
        BrazilLbl = new javax.swing.JLabel();
        CanadaLbl = new javax.swing.JLabel();
        noticeTA = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        Readybtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        CanadaTA = new javax.swing.JTextArea();
        BrazilTA = new javax.swing.JTextArea();
        PeruTA = new javax.swing.JTextArea();
        USATA = new javax.swing.JTextArea();
        BrazilBtn = new javax.swing.JButton();
        USABtn = new javax.swing.JButton();
        CanadaBtn = new javax.swing.JButton();
        PeruBtn = new javax.swing.JButton();
        reminderLbl = new javax.swing.JLabel();
        questLbl = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        ImgLbl = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setMinimumSize(new java.awt.Dimension(604, 570));
        jFrame1.getContentPane().setLayout(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        PeruLbl.setBackground(new java.awt.Color(153, 255, 153));
        PeruLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        PeruLbl.setForeground(new java.awt.Color(255, 255, 255));
        PeruLbl.setText("Do you know Peru?");
        PeruLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        PeruLbl.setOpaque(true);
        getContentPane().add(PeruLbl);
        PeruLbl.setBounds(10, 170, 270, 33);

        USALbl.setBackground(new java.awt.Color(51, 51, 255));
        USALbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        USALbl.setForeground(new java.awt.Color(255, 255, 255));
        USALbl.setText("Do you know USA?");
        USALbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        USALbl.setOpaque(true);
        getContentPane().add(USALbl);
        USALbl.setBounds(10, 170, 270, 33);

        BrazilLbl.setBackground(new java.awt.Color(255, 255, 0));
        BrazilLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        BrazilLbl.setForeground(new java.awt.Color(255, 255, 255));
        BrazilLbl.setText("Do you know Brazil?");
        BrazilLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        BrazilLbl.setOpaque(true);
        getContentPane().add(BrazilLbl);
        BrazilLbl.setBounds(10, 170, 270, 33);

        CanadaLbl.setBackground(new java.awt.Color(255, 51, 51));
        CanadaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        CanadaLbl.setForeground(new java.awt.Color(255, 255, 255));
        CanadaLbl.setText("Do you know Canada?");
        CanadaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        CanadaLbl.setOpaque(true);
        getContentPane().add(CanadaLbl);
        CanadaLbl.setBounds(10, 170, 270, 33);

        noticeTA.setColumns(20);
        noticeTA.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        noticeTA.setRows(5);
        noticeTA.setText("Take notice of these \ntips for your upcoming\n          Quest!");
        noticeTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(noticeTA);
        noticeTA.setBounds(200, 50, 200, 94);

        backBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        backBtn.setText("Back to Menu");
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(150, 190, 170, 60);

        Readybtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        Readybtn.setForeground(new java.awt.Color(255, 255, 255));
        Readybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ready3d.png"))); // NOI18N
        Readybtn.setBorderPainted(false);
        Readybtn.setContentAreaFilled(false);
        Readybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Readybtn);
        Readybtn.setBounds(250, 180, 210, 70);

        nextBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nextBtn.setText("Next Continent");
        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(340, 190, 170, 60);

        CanadaTA.setColumns(20);
        CanadaTA.setRows(5);
        CanadaTA.setText("Ottawa is the capital city of Canada.\nToronto is the largest city in Canada.\nIce-Hockey is the national sport of Canada.\nThe Maple Leaf is the national Symbol of \nCanada.\nCanada's largest export is Maple Syrup.\n");
        CanadaTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(CanadaTA);
        CanadaTA.setBounds(10, 210, 350, 130);

        BrazilTA.setColumns(20);
        BrazilTA.setRows(5);
        BrazilTA.setText("Brasilia is the capital city of Brazil.\nPortuguese is the official language of Brazil.\nSao Paulo is the largest city in Brazil.\nBrazil has the second largest river in the\nworld, the Amazon river.\nFootball is the most popular sport in Brazil\nand they have won the FIFA World Cup 5 times.\nBrazil is the 5th largest country in the world.\nBrazil gained independence from Portugal on \nSeptember 7th, 1822.\nPotuguese explorers discovered Brazil.\nRoman Catholic is the religion of Brazil.");
        BrazilTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(BrazilTA);
        BrazilTA.setBounds(10, 210, 380, 230);

        PeruTA.setColumns(20);
        PeruTA.setRows(5);
        PeruTA.setText("Lima is the capital city of Peru.\nSpanish is the national language of Peru.\nNuevo Sol is the currency used in Peru.\nMachu Picchu, a famous Incan city, is found\nin Peru.\nThe Andes, a major mountain range is also \nfound in Peru.");
        PeruTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(PeruTA);
        PeruTA.setBounds(10, 210, 350, 170);

        USATA.setColumns(20);
        USATA.setRows(5);
        USATA.setText("There are 50 states in the USA.\nNew York is the city with the highest \npopulation in the USA.\nWashington DC is the capital city of the USA.\nGeorge Washington was the first president of\nthe USA.\nThe Dollar is he currency of the USA.\nThe Missouri river is the longest river in the\nUSA.\nThe American flag has 50 stars and 13 stripes.\nIndependence day is on the 4th of July.\nBarrack Obama is the current president of the\nUSA. \n\n");
        USATA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(USATA);
        USATA.setBounds(10, 210, 380, 240);

        BrazilBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        BrazilBtn.setText("Brazil");
        BrazilBtn.setBorderPainted(false);
        BrazilBtn.setContentAreaFilled(false);
        BrazilBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BrazilBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BrazilBtnMouseExited(evt);
            }
        });
        BrazilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrazilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BrazilBtn);
        BrazilBtn.setBounds(440, 380, 110, 33);

        USABtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        USABtn.setText("USA");
        USABtn.setBorderPainted(false);
        USABtn.setContentAreaFilled(false);
        USABtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                USABtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                USABtnMouseExited(evt);
            }
        });
        USABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USABtnActionPerformed(evt);
            }
        });
        getContentPane().add(USABtn);
        USABtn.setBounds(190, 270, 100, 33);

        CanadaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        CanadaBtn.setText("Canada");
        CanadaBtn.setBorderPainted(false);
        CanadaBtn.setContentAreaFilled(false);
        CanadaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CanadaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CanadaBtnMouseExited(evt);
            }
        });
        CanadaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanadaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CanadaBtn);
        CanadaBtn.setBounds(210, 180, 130, 33);

        PeruBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PeruBtn.setText("Peru");
        PeruBtn.setBorderPainted(false);
        PeruBtn.setContentAreaFilled(false);
        PeruBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PeruBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PeruBtnMouseExited(evt);
            }
        });
        PeruBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeruBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PeruBtn);
        PeruBtn.setBounds(310, 390, 90, 33);

        reminderLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        reminderLbl.setText("Hover over discovered countries to learn facts about them");
        reminderLbl.setToolTipText("");
        getContentPane().add(reminderLbl);
        reminderLbl.setBounds(30, 60, 730, 19);

        questLbl.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        questLbl.setText("Try to remember where these countries are, when you are ready, click the ready button.");
        questLbl.setToolTipText("");
        getContentPane().add(questLbl);
        questLbl.setBounds(0, 40, 800, 15);

        scoreLbl.setText("Score: ");
        getContentPane().add(scoreLbl);
        scoreLbl.setBounds(20, 550, 90, 14);

        ImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/NorthandSouthAmerica.png"))); // NOI18N
        getContentPane().add(ImgLbl);
        ImgLbl.setBounds(0, 30, 610, 480);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        WorldMapGUI select = null;
        try {
            select = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(AmericanTutorialGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void ReadybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadybtnActionPerformed
        // TODO add your handling code here:
        questLbl.setText("Where is Canada?");
        BrazilBtn.setText("");
        PeruBtn.setText("");
        CanadaBtn.setText("");
        USABtn.setText("");
        Readybtn.setVisible(false);
        //questLbl.setText("Where is Spain?");
        reminderLbl.setVisible(true);
    }//GEN-LAST:event_ReadybtnActionPerformed

    private void BrazilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrazilBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Brazil")){
            JOptionPane.showMessageDialog(null,"Correct! +5 points!");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is USA?");
            BrazilBtn.setText("Brazil");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_BrazilBtnActionPerformed

    private void USABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USABtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("USA")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
                
                questLbl.setText("Tutorial Complete");
                JOptionPane.showMessageDialog(null, "Congratulations you have completed the Americas map game!!!!");
                backBtn.setVisible(true);
                nextBtn.setVisible(true);
                
            
            
            USABtn.setText("USA");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_USABtnActionPerformed

    private void CanadaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanadaBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Canada")){
            JOptionPane.showMessageDialog(null,"Correct! +5 points!");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is Peru?");
            CanadaBtn.setText("Canada");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }

    }//GEN-LAST:event_CanadaBtnActionPerformed

    private void PeruBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeruBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Peru")){
            JOptionPane.showMessageDialog(null,"Correct! +5 points!");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is Brazil?");
            PeruBtn.setText("Peru");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_PeruBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void CanadaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanadaBtnMouseEntered
        // TODO add your handling code here:
         if(CanadaBtn.getText().contains("Canada")&&Readybtn.isShowing()==false){
        CanadaTA.setVisible(true);
        CanadaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            CanadaTA.setVisible(false);
            CanadaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_CanadaBtnMouseEntered

    private void CanadaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanadaBtnMouseExited
        // TODO add your handling code here:
        CanadaTA.setVisible(false);
        CanadaLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_CanadaBtnMouseExited

    private void PeruBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeruBtnMouseEntered
        // TODO add your handling code here:
         if(PeruBtn.getText().contains("Peru")&&Readybtn.isShowing()==false){
        PeruTA.setVisible(true);
        PeruLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            PeruTA.setVisible(false);
            PeruLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_PeruBtnMouseEntered

    private void PeruBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PeruBtnMouseExited
        // TODO add your handling code here:
        PeruTA.setVisible(false);
        PeruLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_PeruBtnMouseExited

    private void BrazilBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrazilBtnMouseEntered
        // TODO add your handling code here:
        if(BrazilBtn.getText().contains("Brazil")&&Readybtn.isShowing()==false){
        BrazilTA.setVisible(true);
        BrazilLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            BrazilTA.setVisible(false);
            BrazilLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_BrazilBtnMouseEntered

    private void USABtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USABtnMouseEntered
        // TODO add your handling code here:
         if(USABtn.getText().contains("USA")&&Readybtn.isShowing()==false){
        USATA.setVisible(true);
        USALbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            USATA.setVisible(false);
            USALbl.setVisible(false);
            noticeTA.setVisible(false);
        }
        
    }//GEN-LAST:event_USABtnMouseEntered

    private void BrazilBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BrazilBtnMouseExited
        // TODO add your handling code here:
        BrazilTA.setVisible(false);
        BrazilLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_BrazilBtnMouseExited

    private void USABtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_USABtnMouseExited
        // TODO add your handling code here:
        USATA.setVisible(false);
        USALbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_USABtnMouseExited

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmericanTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmericanTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmericanTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmericanTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmericanTutorialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BrazilBtn;
    private javax.swing.JLabel BrazilLbl;
    private javax.swing.JTextArea BrazilTA;
    private javax.swing.JButton CanadaBtn;
    private javax.swing.JLabel CanadaLbl;
    private javax.swing.JTextArea CanadaTA;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel ImgLbl;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton PeruBtn;
    private javax.swing.JLabel PeruLbl;
    private javax.swing.JTextArea PeruTA;
    private javax.swing.JButton Readybtn;
    private javax.swing.JButton USABtn;
    private javax.swing.JLabel USALbl;
    private javax.swing.JTextArea USATA;
    private javax.swing.JButton backBtn;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextArea noticeTA;
    private javax.swing.JLabel questLbl;
    private javax.swing.JLabel reminderLbl;
    private javax.swing.JLabel scoreLbl;
    // End of variables declaration//GEN-END:variables
}
