package continentalconquest;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x13508623
 */
public class AmericasGUI extends javax.swing.JFrame {

    /**
     * Creates new form AmericasGUI
     */
    public AmericasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        BrazilBtn = new javax.swing.JButton();
        USABtn = new javax.swing.JButton();
        CanadaBtn = new javax.swing.JButton();
        PeruBtn = new javax.swing.JButton();
        ImgLbl = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        backBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(20, 280, 100, 33);

        BrazilBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        BrazilBtn.setText("Brazil");
        BrazilBtn.setContentAreaFilled(false);
        BrazilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrazilBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BrazilBtn);
        BrazilBtn.setBounds(430, 390, 130, 33);

        USABtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        USABtn.setText("USA");
        USABtn.setContentAreaFilled(false);
        USABtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USABtnActionPerformed(evt);
            }
        });
        getContentPane().add(USABtn);
        USABtn.setBounds(160, 160, 160, 33);

        CanadaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        CanadaBtn.setText("Canada");
        CanadaBtn.setContentAreaFilled(false);
        CanadaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanadaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CanadaBtn);
        CanadaBtn.setBounds(180, 90, 100, 23);

        PeruBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        PeruBtn.setText("Peru");
        PeruBtn.setContentAreaFilled(false);
        PeruBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeruBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PeruBtn);
        PeruBtn.setBounds(300, 390, 100, 30);

        ImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/NorthandSouthAmerica.png"))); // NOI18N
        getContentPane().add(ImgLbl);
        ImgLbl.setBounds(0, 30, 605, 480);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void USABtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USABtnActionPerformed
        // TODO add your handling code here:
        USAQ start =  new USAQ();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_USABtnActionPerformed

    private void CanadaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanadaBtnActionPerformed
        // TODO add your handling code here:
        CanadaQ start =  new CanadaQ();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CanadaBtnActionPerformed

    private void PeruBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeruBtnActionPerformed
        // TODO add your handling code here:
        PeruQ start =  new PeruQ();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PeruBtnActionPerformed

    private void BrazilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrazilBtnActionPerformed
        // TODO add your handling code here:
        BrazilQ start =  new BrazilQ();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BrazilBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        WorldMapGUI select = null;
        try {
            select = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(AmericasGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AmericasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AmericasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AmericasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AmericasGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AmericasGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BrazilBtn;
    private javax.swing.JButton CanadaBtn;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel ImgLbl;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton PeruBtn;
    private javax.swing.JButton USABtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
