/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13532883
 */
public class AsiaFrame extends javax.swing.JFrame {

    /**
     * Creates new form AsiaFrame
     */
    public AsiaFrame() throws MalformedURLException {
        initComponents();
       // CustomCursor();
    }
public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonindia = new javax.swing.JButton();
        jButtonchina = new javax.swing.JButton();
        jButtonsarabia = new javax.swing.JButton();
        jButtonjapan = new javax.swing.JButton();
        jButtonmongolia = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButtonindia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonindia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonindia.setText("India");
        jButtonindia.setBorderPainted(false);
        jButtonindia.setContentAreaFilled(false);
        jButtonindia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonindiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonindia);
        jButtonindia.setBounds(200, 350, 110, 60);

        jButtonchina.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonchina.setForeground(new java.awt.Color(255, 255, 255));
        jButtonchina.setText("China");
        jButtonchina.setBorderPainted(false);
        jButtonchina.setContentAreaFilled(false);
        jButtonchina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonchinaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonchina);
        jButtonchina.setBounds(330, 270, 130, 70);

        jButtonsarabia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonsarabia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsarabia.setText("Saudi Arabia");
        jButtonsarabia.setBorderPainted(false);
        jButtonsarabia.setContentAreaFilled(false);
        jButtonsarabia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsarabiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsarabia);
        jButtonsarabia.setBounds(-20, 350, 200, 70);

        jButtonjapan.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonjapan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonjapan.setText("Japan");
        jButtonjapan.setBorderPainted(false);
        jButtonjapan.setContentAreaFilled(false);
        jButtonjapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjapanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonjapan);
        jButtonjapan.setBounds(520, 250, 120, 70);

        jButtonmongolia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonmongolia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonmongolia.setText("Mongolia");
        jButtonmongolia.setBorderPainted(false);
        jButtonmongolia.setContentAreaFilled(false);
        jButtonmongolia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmongoliaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmongolia);
        jButtonmongolia.setBounds(330, 200, 180, 60);

        BackBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back ");
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(10, 40, 80, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/asoutl.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 624, 654);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsarabiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsarabiaActionPerformed
        // TODO add your handling code here:
        SaudiArabiaFrame start = new SaudiArabiaFrame();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonsarabiaActionPerformed

    private void jButtonindiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonindiaActionPerformed
        // TODO add your handling code here:
        IndiaFrame start = new IndiaFrame();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonindiaActionPerformed

    private void jButtonmongoliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmongoliaActionPerformed
        // TODO add your handling code here:
        MongoliaFrame start = new MongoliaFrame();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonmongoliaActionPerformed

    private void jButtonchinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonchinaActionPerformed
        // TODO add your handling code here:
        ChinaFrame start = new ChinaFrame();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonchinaActionPerformed

    private void jButtonjapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjapanActionPerformed
        // TODO add your handling code here:
        JapanFrame start = null;
        try {
            start = new JapanFrame();
        } catch (MalformedURLException ex) {
            Logger.getLogger(AsiaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonjapanActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        WorldMapGUI newGUI = null;
        try {
            newGUI = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(EuropeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        newGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsiaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AsiaFrame().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(AsiaFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton jButtonchina;
    private javax.swing.JButton jButtonindia;
    private javax.swing.JButton jButtonjapan;
    private javax.swing.JButton jButtonmongolia;
    private javax.swing.JButton jButtonsarabia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
