/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author x13532883
 */
public class AsiaTutorial extends javax.swing.JFrame {
int score;
    /**
     * Creates new form AsiaTutorial
     */
    public AsiaTutorial() {
        initComponents();
        chinaTA.setVisible(false);
        indiaTA.setVisible(false);
        japanTA.setVisible(false);
        mongoliaTA.setVisible(false);
        saudiarabiaTA.setVisible(false);
        noticeTA.setVisible(false);
        nextBtn.setVisible(false);
        backBtn.setVisible(false);
        chinaLbl.setVisible(false);
        indiaLbl.setVisible(false);
        japanLbl.setVisible(false);
        mongoliaLbl.setVisible(false);
        saudiarabiaLbl.setVisible(false);
        reminderLbl.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questLbl = new javax.swing.JLabel();
        jButtonindia = new javax.swing.JButton();
        jButtonchina = new javax.swing.JButton();
        jButtonsarabia = new javax.swing.JButton();
        jButtonmongolia = new javax.swing.JButton();
        jButtonjapan = new javax.swing.JButton();
        Readybtn = new javax.swing.JButton();
        reminderLbl = new javax.swing.JLabel();
        indiaTA = new javax.swing.JTextArea();
        chinaTA = new javax.swing.JTextArea();
        saudiarabiaTA = new javax.swing.JTextArea();
        japanTA = new javax.swing.JTextArea();
        mongoliaTA = new javax.swing.JTextArea();
        chinaLbl = new javax.swing.JLabel();
        indiaLbl = new javax.swing.JLabel();
        japanLbl = new javax.swing.JLabel();
        mongoliaLbl = new javax.swing.JLabel();
        saudiarabiaLbl = new javax.swing.JLabel();
        russiaBtn = new javax.swing.JButton();
        italyBtn = new javax.swing.JButton();
        turkeyBtn1 = new javax.swing.JButton();
        germanyBtn = new javax.swing.JButton();
        franceBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        noticeTA = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        nextBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        questLbl.setText("Try to remember where these countries are, when you are ready, click the ready button.");
        questLbl.setToolTipText("");
        getContentPane().add(questLbl);
        questLbl.setBounds(0, 24, 500, 30);

        jButtonindia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonindia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonindia.setText("india");
        jButtonindia.setBorderPainted(false);
        jButtonindia.setContentAreaFilled(false);
        jButtonindia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonindiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonindiaMouseExited(evt);
            }
        });
        jButtonindia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonindiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonindia);
        jButtonindia.setBounds(210, 300, 110, 100);

        jButtonchina.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonchina.setForeground(new java.awt.Color(255, 255, 255));
        jButtonchina.setText("china");
        jButtonchina.setBorderPainted(false);
        jButtonchina.setContentAreaFilled(false);
        jButtonchina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonchinaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonchinaMouseExited(evt);
            }
        });
        jButtonchina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonchinaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonchina);
        jButtonchina.setBounds(280, 240, 220, 90);

        jButtonsarabia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonsarabia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonsarabia.setText("saudi arabia");
        jButtonsarabia.setBorderPainted(false);
        jButtonsarabia.setContentAreaFilled(false);
        jButtonsarabia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonsarabiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonsarabiaMouseExited(evt);
            }
        });
        jButtonsarabia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsarabiaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsarabia);
        jButtonsarabia.setBounds(-30, 300, 200, 100);

        jButtonmongolia.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonmongolia.setForeground(new java.awt.Color(255, 255, 255));
        jButtonmongolia.setText("mongolia");
        jButtonmongolia.setBorderPainted(false);
        jButtonmongolia.setContentAreaFilled(false);
        jButtonmongolia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonmongoliaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonmongoliaMouseExited(evt);
            }
        });
        jButtonmongolia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonmongoliaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonmongolia);
        jButtonmongolia.setBounds(320, 160, 180, 70);

        jButtonjapan.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jButtonjapan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonjapan.setText("japan");
        jButtonjapan.setBorderPainted(false);
        jButtonjapan.setContentAreaFilled(false);
        jButtonjapan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonjapanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonjapanMouseExited(evt);
            }
        });
        jButtonjapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonjapanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonjapan);
        jButtonjapan.setBounds(510, 200, 120, 70);

        Readybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ready3d.png"))); // NOI18N
        Readybtn.setBorderPainted(false);
        Readybtn.setContentAreaFilled(false);
        Readybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadybtnActionPerformed(evt);
            }
        });
        getContentPane().add(Readybtn);
        Readybtn.setBounds(210, 360, 210, 80);

        reminderLbl.setText("Hover over discovered countries to learn facts about them");
        reminderLbl.setToolTipText("");
        getContentPane().add(reminderLbl);
        reminderLbl.setBounds(280, 30, 350, 14);

        indiaTA.setColumns(20);
        indiaTA.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        indiaTA.setRows(5);
        indiaTA.setText("The capital of India is New Dehli. The currency \nof India is Rupee. The official language of India\nis Hindi. The main religion of India is Hindu. The\nlife expectancy of India is 63. The percentage of\nearth surface covered by India is 2.4. Tripitakas\nare sacred books of Buddhism. The name of the \ncountry that colonized India is Britain. The East\nIndia Company got dissolved in the year 1858. On \naverage, the amount of people who gather for the \nKumbh Mela Festival is 100 Million");
        getContentPane().add(indiaTA);
        indiaTA.setBounds(260, 360, 350, 170);

        chinaTA.setColumns(20);
        chinaTA.setRows(5);
        chinaTA.setText("The capital of China is Beijing. The \ncurrency of Chinais Renminbi. China hosted\n the Olympic Games in 2008. The official \nlanguage of China is Mandarin. China does \nnot have an official religion. The most \npopular sport of China is table tennis. \nThe most common surname in China is Li. \nFortune cookies first invented in San Francisco.\n45 Billion chopsticks are used every year \nin China. 35 Million people still live in caves \nin China.");
        getContentPane().add(chinaTA);
        chinaTA.setBounds(260, 360, 350, 170);

        saudiarabiaTA.setColumns(20);
        saudiarabiaTA.setRows(5);
        saudiarabiaTA.setText("The capital of Saudi Arabia is Riyadh.\nThe currency of Saudi Arabia is the Saudi \nArabian Riyal.Saudi Arabia is the \nbirthplace of Islam.There are no rivers in \nSaudi Arabia.Universal sufferage was made \nlegal in Saudi Arabia in 2015.");
        getContentPane().add(saudiarabiaTA);
        saudiarabiaTA.setBounds(260, 360, 350, 170);

        japanTA.setColumns(20);
        japanTA.setRows(5);
        japanTA.setText("The capital of Japan is Tokyo. The currency\nof Japan is Yen. The offical language of \nJapan is Japanese. The highest point of \nJapan is Mount Fuji. The national sport of \nJapan is Sumo Wrestling. Japan made up of \n6852 islands. The literacy rate in Japan \n99%. The unemployment rate of Japan is 4%.\nOn average, 1500 earthquakes occur in Japan each year.\nThe national anthem of Japan is Kimigayo.\n");
        getContentPane().add(japanTA);
        japanTA.setBounds(260, 360, 350, 170);

        mongoliaTA.setColumns(20);
        mongoliaTA.setRows(5);
        mongoliaTA.setText("The capital of Mongolia is Ulaan Baatar.\nThe life expectancy of Mongolia is 65.\nThe currency of Mongolia is Tugrik.\nThe official language of Mongolia is Mongolian.\nThe main religion of Mongolia is Buddhism.");
        getContentPane().add(mongoliaTA);
        mongoliaTA.setBounds(260, 360, 350, 170);

        chinaLbl.setBackground(new java.awt.Color(0, 204, 0));
        chinaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        chinaLbl.setForeground(new java.awt.Color(255, 255, 255));
        chinaLbl.setText("Do you know China?");
        chinaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        chinaLbl.setOpaque(true);
        getContentPane().add(chinaLbl);
        chinaLbl.setBounds(260, 320, 270, 33);

        indiaLbl.setBackground(new java.awt.Color(0, 153, 153));
        indiaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        indiaLbl.setForeground(new java.awt.Color(255, 255, 255));
        indiaLbl.setText("Do you know India?");
        indiaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        indiaLbl.setOpaque(true);
        getContentPane().add(indiaLbl);
        indiaLbl.setBounds(260, 320, 270, 33);

        japanLbl.setBackground(new java.awt.Color(0, 153, 153));
        japanLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        japanLbl.setForeground(new java.awt.Color(255, 255, 255));
        japanLbl.setText("Do you know Japan?");
        japanLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        japanLbl.setOpaque(true);
        getContentPane().add(japanLbl);
        japanLbl.setBounds(260, 320, 270, 33);

        mongoliaLbl.setBackground(new java.awt.Color(255, 51, 51));
        mongoliaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        mongoliaLbl.setForeground(new java.awt.Color(255, 255, 255));
        mongoliaLbl.setText("Do you know Poland?");
        mongoliaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mongoliaLbl.setOpaque(true);
        getContentPane().add(mongoliaLbl);
        mongoliaLbl.setBounds(260, 320, 270, 33);

        saudiarabiaLbl.setBackground(new java.awt.Color(255, 51, 51));
        saudiarabiaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        saudiarabiaLbl.setForeground(new java.awt.Color(255, 255, 0));
        saudiarabiaLbl.setText("Do you know Saudi Arabia?");
        saudiarabiaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        saudiarabiaLbl.setOpaque(true);
        getContentPane().add(saudiarabiaLbl);
        saudiarabiaLbl.setBounds(260, 320, 330, 33);

        russiaBtn.setContentAreaFilled(false);
        russiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                russiaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(russiaBtn);
        russiaBtn.setBounds(100, 30, 510, 90);

        italyBtn.setBorderPainted(false);
        italyBtn.setContentAreaFilled(false);
        italyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(italyBtn);
        italyBtn.setBounds(110, 240, 60, 60);

        turkeyBtn1.setContentAreaFilled(false);
        turkeyBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkeyBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(turkeyBtn1);
        turkeyBtn1.setBounds(530, 160, 80, 90);

        germanyBtn.setBorderPainted(false);
        germanyBtn.setContentAreaFilled(false);
        germanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(germanyBtn);
        germanyBtn.setBounds(180, 200, 70, 70);

        franceBtn.setBorderPainted(false);
        franceBtn.setContentAreaFilled(false);
        franceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(franceBtn);
        franceBtn.setBounds(20, 190, 80, 60);

        BackBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back ");
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(0, 60, 80, 30);

        noticeTA.setColumns(20);
        noticeTA.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        noticeTA.setRows(5);
        noticeTA.setText("Take notice of these \ntips for your upcoming\n          Quest!");
        noticeTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(noticeTA);
        noticeTA.setBounds(230, 60, 200, 94);

        backBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back to Menu");
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(140, 60, 170, 60);

        nextBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nextBtn.setForeground(new java.awt.Color(255, 255, 255));
        nextBtn.setText("Next Continent");
        nextBtn.setBorderPainted(false);
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nextBtn);
        nextBtn.setBounds(380, 60, 170, 60);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/asoutl.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 50, 624, 490);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        scoreLbl.setText("Score: ");
        getContentPane().add(scoreLbl);
        scoreLbl.setBounds(0, 180, 90, 14);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReadybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadybtnActionPerformed
        // TODO add your handling code here:

        questLbl.setText("Where is Saudi Arabia?");
        jButtonchina.setText("");
        jButtonsarabia.setText("");
        jButtonindia.setText("");
        jButtonmongolia.setText("");
        jButtonjapan.setText("");
        Readybtn.setVisible(false);
        //questLbl.setText("Where is Spain?");
        reminderLbl.setVisible(true);
    }//GEN-LAST:event_ReadybtnActionPerformed

    private void russiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_russiaBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_russiaBtnActionPerformed

    private void italyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italyBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_italyBtnActionPerformed

    private void turkeyBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkeyBtn1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_turkeyBtn1ActionPerformed

    private void germanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanyBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_germanyBtnActionPerformed

    private void franceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franceBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_franceBtnActionPerformed

    private void jButtonindiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonindiaActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("India")){
            JOptionPane.showMessageDialog(null,"Correct! +5 points!");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is Mongolia?");
            jButtonindia.setText("India");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_jButtonindiaActionPerformed

    private void jButtonchinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonchinaActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("China")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is Japan?");
            jButtonchina.setText("China");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_jButtonchinaActionPerformed

    private void jButtonsarabiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsarabiaActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Saudi Arabia")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is India?");
            jButtonsarabia.setText("Saudi Arabia");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_jButtonsarabiaActionPerformed

    private void jButtonjapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonjapanActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Japan")){
            questLbl.setText("Tutorial Complete");
            JOptionPane.showMessageDialog(null, "Congratulations you have completed the Asia map game!!!!");
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            jButtonjapan.setText("Japan");
            backBtn.setVisible(true);
            nextBtn.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");

        }
    }//GEN-LAST:event_jButtonjapanActionPerformed

    private void jButtonmongoliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonmongoliaActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Mongolia")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            scoreLbl.setText(String.valueOf(score));
            questLbl.setText("Where is China?");
            jButtonmongolia.setText("Mongolia");
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_jButtonmongoliaActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        WorldMapGUI newGUI = null;
        try {
            newGUI = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(EuropeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        newGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        tempGUI temp = new tempGUI();
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void jButtonsarabiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsarabiaMouseEntered
        // TODO add your handling code here:
        if(jButtonsarabia.getText().contains("Saudi Arabia")&&Readybtn.isShowing()==false){
        saudiarabiaTA.setVisible(true);
        saudiarabiaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            saudiarabiaTA.setVisible(false);
            saudiarabiaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_jButtonsarabiaMouseEntered

    private void jButtonsarabiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonsarabiaMouseExited
        // TODO add your handling code here:
            saudiarabiaTA.setVisible(false);
            saudiarabiaLbl.setVisible(false);
            noticeTA.setVisible(false);
    }//GEN-LAST:event_jButtonsarabiaMouseExited

    private void jButtonmongoliaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmongoliaMouseEntered
        // TODO add your handling code here:
        if(jButtonmongolia.getText().contains("Mongolia")&&Readybtn.isShowing()==false){
        mongoliaTA.setVisible(true);
        mongoliaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            mongoliaTA.setVisible(false);
            mongoliaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_jButtonmongoliaMouseEntered

    private void jButtonmongoliaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonmongoliaMouseExited
        // TODO add your handling code here:
            mongoliaTA.setVisible(false);
            mongoliaLbl.setVisible(false);
            noticeTA.setVisible(false);       
    }//GEN-LAST:event_jButtonmongoliaMouseExited

    private void jButtonindiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonindiaMouseEntered
        // TODO add your handling code here:
        if(jButtonindia.getText().contains("India")&&Readybtn.isShowing()==false){
        indiaTA.setVisible(true);
        indiaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            indiaTA.setVisible(false);
            indiaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }        
    }//GEN-LAST:event_jButtonindiaMouseEntered

    private void jButtonindiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonindiaMouseExited
        // TODO add your handling code here:
        indiaTA.setVisible(false);
            indiaLbl.setVisible(false);
            noticeTA.setVisible(false);
    }//GEN-LAST:event_jButtonindiaMouseExited

    private void jButtonchinaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonchinaMouseEntered
        // TODO add your handling code here:
        if(jButtonchina.getText().contains("China")&&Readybtn.isShowing()==false){
        chinaTA.setVisible(true);
        chinaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            chinaTA.setVisible(false);
            chinaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }       
    }//GEN-LAST:event_jButtonchinaMouseEntered

    private void jButtonchinaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonchinaMouseExited
        // TODO add your handling code here:
        chinaTA.setVisible(false);
        chinaLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_jButtonchinaMouseExited

    private void jButtonjapanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonjapanMouseEntered
        // TODO add your handling code here:
        if(jButtonjapan.getText().contains("Japan")&&Readybtn.isShowing()==false){
        japanTA.setVisible(true);
        japanLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            japanTA.setVisible(false);
            japanLbl.setVisible(false);
            noticeTA.setVisible(false);
        }        
    }//GEN-LAST:event_jButtonjapanMouseEntered

    private void jButtonjapanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonjapanMouseExited
        // TODO add your handling code here:
        japanTA.setVisible(false);
        japanLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_jButtonjapanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsiaTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsiaTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsiaTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsiaTutorial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsiaTutorial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton Readybtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel chinaLbl;
    private javax.swing.JTextArea chinaTA;
    private javax.swing.JButton franceBtn;
    private javax.swing.JButton germanyBtn;
    private javax.swing.JLabel indiaLbl;
    private javax.swing.JTextArea indiaTA;
    private javax.swing.JButton italyBtn;
    private javax.swing.JButton jButtonchina;
    private javax.swing.JButton jButtonindia;
    private javax.swing.JButton jButtonjapan;
    private javax.swing.JButton jButtonmongolia;
    private javax.swing.JButton jButtonsarabia;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel japanLbl;
    private javax.swing.JTextArea japanTA;
    private javax.swing.JLabel mongoliaLbl;
    private javax.swing.JTextArea mongoliaTA;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextArea noticeTA;
    private javax.swing.JLabel questLbl;
    private javax.swing.JLabel reminderLbl;
    private javax.swing.JButton russiaBtn;
    private javax.swing.JLabel saudiarabiaLbl;
    private javax.swing.JTextArea saudiarabiaTA;
    private javax.swing.JLabel scoreLbl;
    private javax.swing.JButton turkeyBtn1;
    // End of variables declaration//GEN-END:variables
}
