/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package continentalconquest;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author x13332576
 */
public class AustraliaTutorialGUI extends javax.swing.JFrame {
int score;
private static final String VOICENAME = "kevin16";
    /**
     * Creates new form AustraliaTutorialGUI
     */
    public AustraliaTutorialGUI() {
        initComponents();
        score = 0;
        australiaLbl.setVisible(false);
        newzLbl.setVisible(false);
        ausTA.setVisible(false);
        newzTA.setVisible(false);
        noticeTA.setVisible(false);
        reminderLbl.setVisible(false);
        nextBtn.setVisible(false);
        backBtn.setVisible(false);
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        Readybtn = new javax.swing.JButton();
        australiaBtn = new javax.swing.JButton();
        newzBtn = new javax.swing.JButton();
        reminderLbl = new javax.swing.JLabel();
        australiaLbl = new javax.swing.JLabel();
        noticeTA = new javax.swing.JTextArea();
        newzTA = new javax.swing.JTextArea();
        ausTA = new javax.swing.JTextArea();
        newzLbl = new javax.swing.JLabel();
        questLbl = new javax.swing.JLabel();
        map = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        nextBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nextBtn.setText("Next Continent");
        nextBtn.setContentAreaFilled(false);
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(430, 70, 170, 60);

        backBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        backBtn.setText("Back to Menu");
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(-10, 70, 170, 60);

        Readybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ready3d.png"))); // NOI18N
        Readybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadybtnActionPerformed(evt);
            }
        });
        jPanel1.add(Readybtn);
        Readybtn.setBounds(250, 390, 170, 60);

        australiaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        australiaBtn.setText("Australia");
        australiaBtn.setContentAreaFilled(false);
        australiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                australiaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                australiaBtnMouseExited(evt);
            }
        });
        australiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                australiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(australiaBtn);
        australiaBtn.setBounds(40, 70, 390, 410);

        newzBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        newzBtn.setText("New Zealand");
        newzBtn.setContentAreaFilled(false);
        newzBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newzBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newzBtnMouseExited(evt);
            }
        });
        newzBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newzBtnActionPerformed(evt);
            }
        });
        jPanel1.add(newzBtn);
        newzBtn.setBounds(450, 350, 160, 190);

        reminderLbl.setText("Hover over discovered countries to learn facts about them");
        reminderLbl.setToolTipText("");
        jPanel1.add(reminderLbl);
        reminderLbl.setBounds(270, 40, 350, 14);

        australiaLbl.setBackground(new java.awt.Color(0, 204, 0));
        australiaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        australiaLbl.setForeground(new java.awt.Color(255, 255, 255));
        australiaLbl.setText("Do you know Australia?");
        australiaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        australiaLbl.setOpaque(true);
        jPanel1.add(australiaLbl);
        australiaLbl.setBounds(10, 320, 290, 33);

        noticeTA.setColumns(20);
        noticeTA.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        noticeTA.setRows(5);
        noticeTA.setText("Take notice of these \ntips for your upcoming\n          Quest!");
        noticeTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(noticeTA);
        noticeTA.setBounds(180, 90, 200, 94);

        newzTA.setColumns(20);
        newzTA.setRows(5);
        newzTA.setText("New Zealand is a famous country for many reasons.\nFirstly, it is home to the legendary rugby team the \n\"All Blacks\". The incredible movie series \"The Lord of\nthe rings\" was also filmed here. New Zealand's capital\nis Wellington. It has a small population of 4 million and\nis part of the larger Commonwealth empire. ");
        jPanel1.add(newzTA);
        newzTA.setBounds(10, 360, 400, 170);

        ausTA.setColumns(20);
        ausTA.setRows(5);
        ausTA.setText("Australia is one of the worlds biggest countries. \nIt has a huge population of 23 million. Its capital \ncity is Canberra. Australia is home to many \nanimals such as the kangaroo, which grows babies \nin a pouch. It also contains the largest coral reef\nin the world, called \"The Great Barrier Reef\". ");
        jPanel1.add(ausTA);
        ausTA.setBounds(10, 360, 410, 170);

        newzLbl.setBackground(new java.awt.Color(255, 51, 51));
        newzLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        newzLbl.setForeground(new java.awt.Color(255, 255, 255));
        newzLbl.setText("Do you know New Zealand?");
        newzLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        newzLbl.setOpaque(true);
        jPanel1.add(newzLbl);
        newzLbl.setBounds(10, 320, 340, 33);

        questLbl.setText("Try to remember where these countries are, when you are ready, click the ready button.");
        questLbl.setToolTipText("");
        jPanel1.add(questLbl);
        questLbl.setBounds(10, 40, 490, 14);

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/tutmapAus.png"))); // NOI18N
        jPanel1.add(map);
        map.setBounds(0, 56, 620, 480);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/testerino.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        jPanel1.add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        jPanel1.add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        tempGUI temp = new tempGUI();
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void ReadybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadybtnActionPerformed
        // TODO add your handling code here:

        australiaBtn.setText("");
        newzBtn.setText("");
   
        Readybtn.setVisible(false);
        questLbl.setText("Where is New Zealand?");
        reminderLbl.setVisible(true);
    }//GEN-LAST:event_ReadybtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void newzBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newzBtnActionPerformed
        // TODO add your handling code here:
         if(questLbl.getText().contains("New Zealand")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            
            questLbl.setText("Where is Australia?");
            newzBtn.setText("New Zealand");   
        }
            else if(newzBtn.getText().contains("New")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            try{
                //voice.speak("Learn these tips about");
                voice.speak(newzTA.getText());
               // voice.speak("for your upcoming adventure!");
            }
            catch(Exception e){
            }
            /*reference of this code from https://www.youtube.com/watch?v=swuYhvwHw9w
            edited by author Declan Casey
            */
        } 
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_newzBtnActionPerformed

    private void australiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_australiaBtnActionPerformed
        // TODO add your handling code here:
    if(questLbl.getText().contains("Australia")){
            JOptionPane.showMessageDialog(null, "Correct! +5 points");
            score=score+5;
            questLbl.setText("Where is Australia?");
            australiaBtn.setText("Australia");    
    }
    else if(australiaBtn.getText().contains("Aus")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            try{
                //voice.speak("Learn these tips about");
                voice.speak(ausTA.getText());
               // voice.speak("for your upcoming adventure!");
            }
            catch(Exception e){
            }
            /*reference of this code from https://www.youtube.com/watch?v=swuYhvwHw9w
            edited by author Declan Casey
            */
        } 
            
        
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }        
        
    }//GEN-LAST:event_australiaBtnActionPerformed

    private void australiaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_australiaBtnMouseEntered
        // TODO add your handling code here:
           if(australiaBtn.getText().contains("Australia")&&Readybtn.isShowing()==false){
        ausTA.setVisible(true);
        australiaLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
             else{
            ausTA.setVisible(false);
            australiaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    
    }//GEN-LAST:event_australiaBtnMouseEntered

    private void newzBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newzBtnMouseEntered
        // TODO add your handling code here:
        if(newzBtn.getText().contains("New")&&Readybtn.isShowing()==false){
            newzTA.setVisible(true);
            newzLbl.setVisible(true);
            noticeTA.setVisible(true);
        }
        else{
            newzTA.setVisible(false);
            newzLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_newzBtnMouseEntered

    private void newzBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newzBtnMouseExited
        // TODO add your handling code here:
            newzTA.setVisible(false);
            newzLbl.setVisible(false);
            noticeTA.setVisible(false);
    }//GEN-LAST:event_newzBtnMouseExited

    private void australiaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_australiaBtnMouseExited
        // TODO add your handling code here:
            ausTA.setVisible(false);
            australiaLbl.setVisible(false);
            noticeTA.setVisible(false);  
    }//GEN-LAST:event_australiaBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AustraliaTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AustraliaTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AustraliaTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AustraliaTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AustraliaTutorialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton Readybtn;
    private javax.swing.JTextArea ausTA;
    private javax.swing.JButton australiaBtn;
    private javax.swing.JLabel australiaLbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel map;
    private javax.swing.JButton newzBtn;
    private javax.swing.JLabel newzLbl;
    private javax.swing.JTextArea newzTA;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextArea noticeTA;
    private javax.swing.JLabel questLbl;
    private javax.swing.JLabel reminderLbl;
    // End of variables declaration//GEN-END:variables
}
