/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13532883
 */
public class ChinaFrame extends javax.swing.JFrame {
    String question;
    int count;
    /**
     * Creates new form ChinaFrame
     */
    public ChinaFrame() {
        initComponents();
        question="";
        count = 0;
           try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel,score from Question where country = 'china' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = questionlbl.getText();
                questionlbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    answer1.setText(arr[0]);
                    answer2.setText(arr[1]);
                    answer3.setText(arr[2]);
                    answer4.setText(arr[3]);
                }

            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questionlbl = new javax.swing.JLabel();
        jButtonback = new javax.swing.JButton();
        answer1 = new javax.swing.JButton();
        answer2 = new javax.swing.JButton();
        answer3 = new javax.swing.JButton();
        answer4 = new javax.swing.JButton();
        Scorelbl = new javax.swing.JLabel();
        bgimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(424, 531));
        getContentPane().setLayout(null);

        questionlbl.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        questionlbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        getContentPane().add(questionlbl);
        questionlbl.setBounds(40, 90, 370, 220);

        jButtonback.setText("BACK");
        jButtonback.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jButtonback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonbackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonback);
        jButtonback.setBounds(10, 11, 90, 40);

        answer1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        answer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1ActionPerformed(evt);
            }
        });
        getContentPane().add(answer1);
        answer1.setBounds(40, 360, 130, 50);

        answer2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        answer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2ActionPerformed(evt);
            }
        });
        getContentPane().add(answer2);
        answer2.setBounds(280, 360, 130, 50);

        answer3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        answer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3ActionPerformed(evt);
            }
        });
        getContentPane().add(answer3);
        answer3.setBounds(40, 470, 130, 50);

        answer4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        answer4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4ActionPerformed(evt);
            }
        });
        getContentPane().add(answer4);
        answer4.setBounds(280, 470, 130, 50);

        Scorelbl.setText("jLabel1");
        getContentPane().add(Scorelbl);
        Scorelbl.setBounds(300, 20, 80, 20);

        bgimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/chinaflag.jpg"))); // NOI18N
        getContentPane().add(bgimage);
        bgimage.setBounds(0, 0, 430, 531);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonbackActionPerformed
        // TODO add your handling code here:
        AsiaFrame start = null;
        try {
            start = new AsiaFrame();
        } catch (MalformedURLException ex) {
            Logger.getLogger(ChinaFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonbackActionPerformed

    private void answer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1ActionPerformed
        // TODO add your handling code here:
        try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'china' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionlbl.getText();
questionlbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answer1.setText(arr[0]);
answer2.setText(arr[1]);
answer3.setText(arr[2]);
answer4.setText(arr[3]); 
}

if(arr[0].equals(rs.getString("answer"))){
count++;
Scorelbl.setText("Score:"+count);
}
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answer1ActionPerformed

    private void answer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2ActionPerformed
        // TODO add your handling code here:
                try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'china' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionlbl.getText();
questionlbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answer1.setText(arr[0]);
answer2.setText(arr[1]);
answer3.setText(arr[2]);
answer4.setText(arr[3]); 
}

if(arr[0].equals(rs.getString("answer"))){
count++;
Scorelbl.setText("Score:"+count);
}
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answer2ActionPerformed

    private void answer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3ActionPerformed
        // TODO add your handling code here:
                try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'china' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionlbl.getText();
questionlbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answer1.setText(arr[0]);
answer2.setText(arr[1]);
answer3.setText(arr[2]);
answer4.setText(arr[3]); 
}

if(arr[0].equals(rs.getString("answer"))){
count++;
Scorelbl.setText("Score:"+count);
}
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answer3ActionPerformed

    private void answer4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4ActionPerformed
        // TODO add your handling code here:
                try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'china' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionlbl.getText();
questionlbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answer1.setText(arr[0]);
answer2.setText(arr[1]);
answer3.setText(arr[2]);
answer4.setText(arr[3]); 
}

if(arr[0].equals(rs.getString("answer"))){
count++;
Scorelbl.setText("Score:"+count);
}
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answer4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChinaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChinaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChinaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChinaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChinaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Scorelbl;
    private javax.swing.JButton answer1;
    private javax.swing.JButton answer2;
    private javax.swing.JButton answer3;
    private javax.swing.JButton answer4;
    private javax.swing.JLabel bgimage;
    private javax.swing.JButton jButtonback;
    private javax.swing.JLabel questionlbl;
    // End of variables declaration//GEN-END:variables
}
