/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13564737
 */
public class EuropeGUI extends javax.swing.JFrame {

    /**
     * Creates new form EuropeGUI
     */
    public EuropeGUI() throws MalformedURLException {
        initComponents();
       //  CustomCursor();
        
        
    }
public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        dividerLbl = new javax.swing.JLabel();
        polandBtn = new javax.swing.JButton();
        icelandBtn = new javax.swing.JButton();
        irelandBtn = new javax.swing.JButton();
        spainBtn = new javax.swing.JButton();
        russiaBtn = new javax.swing.JButton();
        mapLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BackBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 540));
        setResizable(false);
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(51, 51, 255));
        titleLbl.setText("Europe");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(230, 50, 120, 40);

        dividerLbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(dividerLbl);
        dividerLbl.setBounds(0, 90, 90, 390);

        polandBtn.setBackground(new java.awt.Color(255, 255, 255));
        polandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        polandBtn.setForeground(new java.awt.Color(51, 51, 255));
        polandBtn.setText("Poland");
        polandBtn.setBorderPainted(false);
        polandBtn.setContentAreaFilled(false);
        polandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polandBtnActionPerformed(evt);
            }
        });
        getContentPane().add(polandBtn);
        polandBtn.setBounds(360, 290, 110, 33);

        icelandBtn.setBackground(new java.awt.Color(255, 255, 255));
        icelandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        icelandBtn.setForeground(new java.awt.Color(51, 51, 255));
        icelandBtn.setText("Iceland");
        icelandBtn.setBorderPainted(false);
        icelandBtn.setContentAreaFilled(false);
        icelandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icelandBtnActionPerformed(evt);
            }
        });
        getContentPane().add(icelandBtn);
        icelandBtn.setBounds(90, 140, 120, 33);

        irelandBtn.setBackground(new java.awt.Color(255, 255, 255));
        irelandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        irelandBtn.setForeground(new java.awt.Color(51, 51, 255));
        irelandBtn.setText("Ireland");
        irelandBtn.setBorderPainted(false);
        irelandBtn.setContentAreaFilled(false);
        irelandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irelandBtnActionPerformed(evt);
            }
        });
        getContentPane().add(irelandBtn);
        irelandBtn.setBounds(100, 260, 130, 33);

        spainBtn.setBackground(new java.awt.Color(255, 255, 255));
        spainBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        spainBtn.setForeground(new java.awt.Color(51, 51, 255));
        spainBtn.setText("Spain");
        spainBtn.setBorderPainted(false);
        spainBtn.setContentAreaFilled(false);
        spainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spainBtnActionPerformed(evt);
            }
        });
        getContentPane().add(spainBtn);
        spainBtn.setBounds(130, 410, 100, 33);

        russiaBtn.setBackground(new java.awt.Color(255, 255, 255));
        russiaBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        russiaBtn.setForeground(new java.awt.Color(51, 51, 255));
        russiaBtn.setText("Russia");
        russiaBtn.setBorderPainted(false);
        russiaBtn.setContentAreaFilled(false);
        russiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                russiaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(russiaBtn);
        russiaBtn.setBounds(460, 220, 130, 33);

        mapLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/europe_1_1.png"))); // NOI18N
        mapLbl.setText("jLabel1");
        getContentPane().add(mapLbl);
        mapLbl.setBounds(70, 90, 560, 400);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 90, 100, 450);

        BackBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        BackBtn.setText("Back ");
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(0, 30, 80, 30);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(100, 90, 520, 430);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(0, 480, 620, 60);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void irelandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irelandBtnActionPerformed
        // TODO add your handling code here:
        IrelandGUI ireland = new IrelandGUI();
        ireland.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_irelandBtnActionPerformed

    private void icelandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icelandBtnActionPerformed
        // TODO add your handling code here:
        IcelandGUI iceland = new IcelandGUI();
        iceland.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_icelandBtnActionPerformed

    private void polandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polandBtnActionPerformed
        // TODO add your handling code here:
        PolandGUI poland = new PolandGUI();
        poland.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_polandBtnActionPerformed

    private void spainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spainBtnActionPerformed
        // TODO add your handling code here:
        SpainGUI spain = new SpainGUI();
        spain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_spainBtnActionPerformed

    private void russiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_russiaBtnActionPerformed
        // TODO add your handling code here:
        RussiaGUI russia = new RussiaGUI();
        russia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_russiaBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        WorldMapGUI newGUI = null;
        try {
            newGUI = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(EuropeGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        newGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EuropeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EuropeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EuropeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EuropeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EuropeGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(EuropeGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JLabel dividerLbl;
    private javax.swing.JButton icelandBtn;
    private javax.swing.JButton irelandBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel mapLbl;
    private javax.swing.JButton polandBtn;
    private javax.swing.JButton russiaBtn;
    private javax.swing.JButton spainBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
