/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import javax.swing.JOptionPane;
import java.io.*;
import com.sun.speech.freetts.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
/*source for imported jar files: 
    http://freetts.sourceforge.net/docs/index.php#voices_available
*/


/**
 *
 * @author Ingrid Trant
 */
public class EuropeTutorialGUI extends javax.swing.JFrame {
    int click;
    /**
     * Creates new form tutorialGUI
     */
    public EuropeTutorialGUI() {
        initComponents();
        backBtn.setVisible(false);
        spainTA.setVisible(false);
        nextBtn.setVisible(false);
        spainLbl.setVisible(false);
        irelandLbl.setVisible(false);
        icelandLbl.setVisible(false);
        russiaLbl.setVisible(false);
        polandLbl.setVisible(false);
        irelandTA.setVisible(false);
        icelandTA.setVisible(false);
        russiaTA.setVisible(false);
        polandTA.setVisible(false);
        noticeTA.setVisible(false);
        reminderLbl.setVisible(false);
        //state = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        reminderLbl = new javax.swing.JLabel();
        irelandLbl = new javax.swing.JLabel();
        polandTA = new javax.swing.JTextArea();
        russiaTA = new javax.swing.JTextArea();
        irelandTA = new javax.swing.JTextArea();
        icelandTA = new javax.swing.JTextArea();
        spainTA = new javax.swing.JTextArea();
        noticeTA = new javax.swing.JTextArea();
        Readybtn = new javax.swing.JButton();
        russiaLbl = new javax.swing.JLabel();
        icelandLbl = new javax.swing.JLabel();
        polandLbl = new javax.swing.JLabel();
        spainLbl = new javax.swing.JLabel();
        nextBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        scandanavianBtn = new javax.swing.JButton();
        turkeyBtn = new javax.swing.JButton();
        italyBtn = new javax.swing.JButton();
        germanyBtn = new javax.swing.JButton();
        franceBtn = new javax.swing.JButton();
        questLbl = new javax.swing.JLabel();
        icelandBtn = new javax.swing.JButton();
        irelandBtn = new javax.swing.JButton();
        spainBtn = new javax.swing.JButton();
        polandBtn = new javax.swing.JButton();
        russiaBtn = new javax.swing.JButton();
        map = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        reminderLbl.setText("Hover over discovered countries to learn facts about them");
        reminderLbl.setToolTipText("");
        jPanel1.add(reminderLbl);
        reminderLbl.setBounds(270, 40, 350, 14);

        irelandLbl.setBackground(new java.awt.Color(0, 204, 0));
        irelandLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        irelandLbl.setForeground(new java.awt.Color(255, 255, 255));
        irelandLbl.setText("Do you know Ireland?");
        irelandLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        irelandLbl.setOpaque(true);
        jPanel1.add(irelandLbl);
        irelandLbl.setBounds(260, 320, 270, 33);

        polandTA.setColumns(20);
        polandTA.setLineWrap(true);
        polandTA.setRows(5);
        polandTA.setText("The capital of Poland is Warsaw. Poland's \ncapital used to be Krakow. The longest \nriver in Poland is the Vistula. The Uefa \nEuro 2012 football championship took place in cities across \nPoland. After World War II Poland became \npart of the Soviet Union. Poland gained its independence from the Soviet Union in  1989.");
        jPanel1.add(polandTA);
        polandTA.setBounds(260, 360, 350, 170);

        russiaTA.setColumns(20);
        russiaTA.setLineWrap(true);
        russiaTA.setRows(5);
        russiaTA.setText("The capital of Russia is Moscow. It is on\nboth the continent of Europe and Asia.\nRussia is home to many of the world's \ngreatest natural wonders such as the \nworld's largest lake, Lake Baikal. It is \nalso home to the tallest mountains in Europe,\nMount Elbrus. The Scandanavians were the \nfirst people to settle(conquer)in Russia.\n");
        jPanel1.add(russiaTA);
        russiaTA.setBounds(260, 360, 350, 170);

        irelandTA.setColumns(20);
        irelandTA.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        irelandTA.setLineWrap(true);
        irelandTA.setRows(5);
        irelandTA.setText("The Spire is at the heart of the capital,\nDublin, on O'Connell Street. The biggest lake in Ireland is Lough Neagh and the biggest mountain is Carrauntoohil. Hurling is a famous irish sport and one of the best teams is Killkenny a.k.a\n'The Cats'. The Taoiseach comes from the county\nof Mayo. The Great Famine ended in 1852. \nThe famous comedy 'Father Ted' was on a fictional island called Craggy Island.");
        jPanel1.add(irelandTA);
        irelandTA.setBounds(260, 360, 360, 170);

        icelandTA.setColumns(20);
        icelandTA.setLineWrap(true);
        icelandTA.setRows(5);
        icelandTA.setText("The capital of Iceland is Reykjavik. A \nfamous tourist location is a hot spring, \ncalled the Blue Lagoon. The Aurora Borealis a.k.a the Northern Lights can often be seen lighting up the sky. There are 36 \ndifferent letters in the Icelandic alphabet, 10 more \nthan english. The Vikings were the first \npeople to settle in Iceland.");
        jPanel1.add(icelandTA);
        icelandTA.setBounds(260, 360, 360, 170);

        spainTA.setColumns(20);
        spainTA.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        spainTA.setLineWrap(true);
        spainTA.setRows(5);
        spainTA.setText("The capital of Spain is Madrid. Spain is \nfamous for bull fighting. In this sport, a\nmatador fights a bull to death. Another sport\nthey are famous for is football. Two of their \nbest teams are Barcelona, who play at the \nNou Camp and Real Madrid, who play at the \nBernabeau.The country's neighbours are Portugal \nand France. Spain had a brutal civil war in 1936, where an estimated 200,000 people died. ");
        jPanel1.add(spainTA);
        spainTA.setBounds(260, 360, 360, 170);

        noticeTA.setColumns(20);
        noticeTA.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        noticeTA.setRows(5);
        noticeTA.setText("Take notice of these \ntips for your upcoming\n          Quest!");
        noticeTA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(noticeTA);
        noticeTA.setBounds(180, 90, 200, 94);

        Readybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ready3d.png"))); // NOI18N
        Readybtn.setBorderPainted(false);
        Readybtn.setContentAreaFilled(false);
        Readybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReadybtnActionPerformed(evt);
            }
        });
        jPanel1.add(Readybtn);
        Readybtn.setBounds(200, 390, 230, 60);

        russiaLbl.setBackground(new java.awt.Color(0, 153, 153));
        russiaLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        russiaLbl.setForeground(new java.awt.Color(255, 255, 255));
        russiaLbl.setText("Do you know Russia?");
        russiaLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        russiaLbl.setOpaque(true);
        jPanel1.add(russiaLbl);
        russiaLbl.setBounds(260, 320, 270, 33);

        icelandLbl.setBackground(new java.awt.Color(0, 153, 153));
        icelandLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        icelandLbl.setForeground(new java.awt.Color(255, 255, 255));
        icelandLbl.setText("Do you know Iceland?");
        icelandLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        icelandLbl.setOpaque(true);
        jPanel1.add(icelandLbl);
        icelandLbl.setBounds(260, 320, 270, 33);

        polandLbl.setBackground(new java.awt.Color(255, 51, 51));
        polandLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        polandLbl.setForeground(new java.awt.Color(255, 255, 255));
        polandLbl.setText("Do you know Poland?");
        polandLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        polandLbl.setOpaque(true);
        jPanel1.add(polandLbl);
        polandLbl.setBounds(260, 320, 270, 33);

        spainLbl.setBackground(new java.awt.Color(255, 51, 51));
        spainLbl.setFont(new java.awt.Font("Old English Text MT", 0, 28)); // NOI18N
        spainLbl.setForeground(new java.awt.Color(255, 255, 0));
        spainLbl.setText("Do you know Spain?");
        spainLbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        spainLbl.setOpaque(true);
        jPanel1.add(spainLbl);
        spainLbl.setBounds(260, 320, 270, 33);

        nextBtn.setText("Next Continent");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextBtn);
        nextBtn.setBounds(350, 90, 170, 60);

        backBtn.setText("Back to Menu");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        jPanel1.add(backBtn);
        backBtn.setBounds(140, 90, 170, 60);

        scandanavianBtn.setBorderPainted(false);
        scandanavianBtn.setContentAreaFilled(false);
        scandanavianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scandanavianBtnActionPerformed(evt);
            }
        });
        jPanel1.add(scandanavianBtn);
        scandanavianBtn.setBounds(160, 60, 200, 190);

        turkeyBtn.setBorderPainted(false);
        turkeyBtn.setContentAreaFilled(false);
        turkeyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkeyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(turkeyBtn);
        turkeyBtn.setBounds(420, 370, 200, 170);

        italyBtn.setBorderPainted(false);
        italyBtn.setContentAreaFilled(false);
        italyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                italyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(italyBtn);
        italyBtn.setBounds(150, 330, 350, 200);

        germanyBtn.setBorderPainted(false);
        germanyBtn.setContentAreaFilled(false);
        germanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                germanyBtnActionPerformed(evt);
            }
        });
        jPanel1.add(germanyBtn);
        germanyBtn.setBounds(170, 60, 100, 330);

        franceBtn.setBorderPainted(false);
        franceBtn.setContentAreaFilled(false);
        franceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                franceBtnActionPerformed(evt);
            }
        });
        jPanel1.add(franceBtn);
        franceBtn.setBounds(110, 140, 80, 280);

        questLbl.setBackground(new java.awt.Color(255, 255, 255));
        questLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        questLbl.setText("Try to remember where these countries are, when you are ready, click the ready button.");
        questLbl.setToolTipText("");
        jPanel1.add(questLbl);
        questLbl.setBounds(10, 40, 630, 15);

        icelandBtn.setBackground(new java.awt.Color(255, 255, 255));
        icelandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        icelandBtn.setForeground(new java.awt.Color(51, 51, 255));
        icelandBtn.setText("Iceland");
        icelandBtn.setBorderPainted(false);
        icelandBtn.setContentAreaFilled(false);
        icelandBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icelandBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icelandBtnMouseExited(evt);
            }
        });
        icelandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icelandBtnActionPerformed(evt);
            }
        });
        jPanel1.add(icelandBtn);
        icelandBtn.setBounds(30, 80, 120, 33);

        irelandBtn.setBackground(new java.awt.Color(255, 255, 255));
        irelandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        irelandBtn.setForeground(new java.awt.Color(51, 51, 255));
        irelandBtn.setText("Ireland");
        irelandBtn.setBorderPainted(false);
        irelandBtn.setContentAreaFilled(false);
        irelandBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                irelandBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                irelandBtnMouseExited(evt);
            }
        });
        irelandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irelandBtnActionPerformed(evt);
            }
        });
        jPanel1.add(irelandBtn);
        irelandBtn.setBounds(10, 230, 110, 50);

        spainBtn.setBackground(new java.awt.Color(255, 255, 255));
        spainBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        spainBtn.setForeground(new java.awt.Color(51, 51, 255));
        spainBtn.setText("Spain");
        spainBtn.setBorderPainted(false);
        spainBtn.setContentAreaFilled(false);
        spainBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                spainBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                spainBtnMouseExited(evt);
            }
        });
        spainBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spainBtnActionPerformed(evt);
            }
        });
        jPanel1.add(spainBtn);
        spainBtn.setBounds(30, 420, 100, 70);

        polandBtn.setBackground(new java.awt.Color(255, 255, 255));
        polandBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        polandBtn.setForeground(new java.awt.Color(51, 51, 255));
        polandBtn.setText("Poland");
        polandBtn.setBorderPainted(false);
        polandBtn.setContentAreaFilled(false);
        polandBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                polandBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                polandBtnMouseExited(evt);
            }
        });
        polandBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polandBtnActionPerformed(evt);
            }
        });
        jPanel1.add(polandBtn);
        polandBtn.setBounds(270, 260, 110, 50);

        russiaBtn.setBackground(new java.awt.Color(255, 255, 255));
        russiaBtn.setFont(new java.awt.Font("Old English Text MT", 1, 24)); // NOI18N
        russiaBtn.setForeground(new java.awt.Color(51, 51, 255));
        russiaBtn.setText("Russia");
        russiaBtn.setBorderPainted(false);
        russiaBtn.setContentAreaFilled(false);
        russiaBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                russiaBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                russiaBtnMouseExited(evt);
            }
        });
        russiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                russiaBtnActionPerformed(evt);
            }
        });
        jPanel1.add(russiaBtn);
        russiaBtn.setBounds(410, 73, 170, 200);

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/blank_europe_map.gif"))); // NOI18N
        jPanel1.add(map);
        map.setBounds(0, 56, 620, 480);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/testerino.png"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        jPanel1.add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        jPanel1.add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private static final String VOICENAME = "kevin16";
    /*reference of this code from https://www.youtube.com/watch?v=swuYhvwHw9w
    */
    
    
    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void icelandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icelandBtnActionPerformed
        // TODO add your handling code here:
       if(questLbl.getText().contains("Iceland")){
            JOptionPane.showMessageDialog(null, "Correct! +1");
            questLbl.setText("Where is Poland?");
            icelandBtn.setText("Iceland");
            
              try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set score = score+1 where p_sel='Y';";
            st.executeUpdate(update);
            /* */
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
              
        }
       else if(icelandBtn.getText().contains("Iceland")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            try{
                //voice.speak("Learn these tips about");
                voice.speak(icelandTA.getText());
               // voice.speak("for your upcoming adventure!");
            }
            catch(Exception e){
            }
            /*reference of this code from https://www.youtube.com/watch?v=swuYhvwHw9w
            edited by author Declan Casey
            */
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_icelandBtnActionPerformed

    private void irelandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irelandBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Ireland")){
            JOptionPane.showMessageDialog(null, "Correct! +1");
            questLbl.setText("Where is Russia?");
            irelandBtn.setText("Ireland");
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set score = score+1 where p_sel='Y';";
            st.executeUpdate(update);
            /* */
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        }
        else if(irelandBtn.getText().contains("Ireland")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            try{
               // voice.speak("Learn these tips about");
                voice.speak(irelandTA.getText());
               // voice.speak("for your upcoming adventure!");   
            }
            catch(Exception e){

            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_irelandBtnActionPerformed

    private void spainBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spainBtnActionPerformed
        // TODO add your handling code here:
      if(questLbl.getText().contains("Spain")){
          JOptionPane.showMessageDialog(null,"Correct! +1");
          questLbl.setText("Where is Ireland?");
          spainBtn.setText("Spain");
               try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set score = score+1 where p_sel='Y';";
            st.executeUpdate(update);
            /* */
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
                }
     
      else if(spainBtn.getText().contains("Spain")){
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        voice.allocate();
          try{
            //voice.speak("Learn these tips about");
            voice.speak(spainTA.getText());
           // voice.speak("for your upcoming adventure!");
        }
        catch(Exception e){
            
        }
          
         // JOptionPane.showMessageDialog(null, "Oops, Try again!");
      }
      else{
          JOptionPane.showMessageDialog(null, "Oops, Try again!");
      }
    }//GEN-LAST:event_spainBtnActionPerformed

    private void polandBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polandBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Poland")){
            JOptionPane.showMessageDialog(null, "Correct! +1");
            questLbl.setText("Game Over");
            JOptionPane.showMessageDialog(null, "Congratulations you have completed the Europe map game!!!!");
            polandBtn.setText("Poland");
            backBtn.setVisible(true);
            nextBtn.setVisible(true);
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set score = score+1 where p_sel='Y';";
            st.executeUpdate(update);
            /* */
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        }
        //elseif(polandTA.setVisible(true)){}
        else if(polandBtn.getText().contains("Poland")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            /*String line[];
            line= polandBtn.getText().split("\\r?\\.");
            System.out.println(line);*/
            try{
               // voice.speak("Learn these tips about");
                voice.speak(polandTA.getText());
                //voice.speak("for your upcoming adventure!");
                
            }
            catch(Exception e){

            }
        }
        else{
            
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
            
        }
    }//GEN-LAST:event_polandBtnActionPerformed

    private void russiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_russiaBtnActionPerformed
        // TODO add your handling code here:
        if(questLbl.getText().contains("Russia")){
            JOptionPane.showMessageDialog(null, "Correct! +1");
            questLbl.setText("Where is Iceland?");
            russiaBtn.setText("Russia");
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set score = score+1 where p_sel='Y';";
            st.executeUpdate(update);
            /* */
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        }
        else if(russiaBtn.getText().contains("Russia")){
            Voice voice;
            VoiceManager vm = VoiceManager.getInstance();
            voice = vm.getVoice(VOICENAME);
            voice.allocate();
            //click++;
            //if(click % 2 == 1){
                try{
                voice.speak(russiaTA.getText());
                }
                catch(Exception e){

                }
            //}
            /*else{
                try{
                    
                voice.speak(" ");
                }
                catch(Exception e){
                    
                }
            }*/
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Oops, Try again!");
        }
    }//GEN-LAST:event_russiaBtnActionPerformed

    private void ReadybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReadybtnActionPerformed
        // TODO add your handling code here:
        icelandBtn.setText("");
        irelandBtn.setText("");
        russiaBtn.setText("");
        polandBtn.setText("");
        spainBtn.setText("");
        Readybtn.setVisible(false);
        questLbl.setText("Where is Spain?");
        reminderLbl.setVisible(true);
    }//GEN-LAST:event_ReadybtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        tempGUI temp = new tempGUI();
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void franceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_franceBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_franceBtnActionPerformed

    private void germanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_germanyBtnActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_germanyBtnActionPerformed

    private void italyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italyBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_italyBtnActionPerformed

    private void turkeyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkeyBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_turkeyBtnActionPerformed

    private void scandanavianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scandanavianBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Oops, Try again!");
    }//GEN-LAST:event_scandanavianBtnActionPerformed

    private void spainBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spainBtnMouseEntered
        // TODO add your handling code here:
        if(spainBtn.getText().contains("Spain")&&Readybtn.isShowing()==false){
        spainTA.setVisible(true);
        spainLbl.setVisible(true);
        noticeTA.setVisible(true);
        }
        else{
            spainTA.setVisible(false);
            spainLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_spainBtnMouseEntered

    private void spainBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spainBtnMouseExited
        // TODO add your handling code here:
        spainTA.setVisible(false);
        spainLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_spainBtnMouseExited

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextBtnActionPerformed

    private void polandBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polandBtnMouseEntered
        // TODO add your handling code here:
        if(polandBtn.getText().contains("Poland")&&Readybtn.isShowing()==false){
            polandTA.setVisible(true);
            polandLbl.setVisible(true);
            noticeTA.setVisible(true);
        }
        else{
            polandTA.setVisible(false);
            polandLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_polandBtnMouseEntered

    private void polandBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polandBtnMouseExited
        // TODO add your handling code here:
        polandTA.setVisible(false);
        polandLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_polandBtnMouseExited

    private void russiaBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_russiaBtnMouseEntered
        // TODO add your handling code here:
        if(russiaBtn.getText().contains("Russia")&&Readybtn.isShowing()==false){
            russiaTA.setVisible(true);
            russiaLbl.setVisible(true);
            noticeTA.setVisible(true);
        }
        else{
            russiaTA.setVisible(false);
            russiaLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_russiaBtnMouseEntered

    private void russiaBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_russiaBtnMouseExited
        // TODO add your handling code here:
        russiaTA.setVisible(false);
        russiaLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_russiaBtnMouseExited

    private void irelandBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irelandBtnMouseEntered
        // TODO add your handling code here:
        if(irelandBtn.getText().contains("Ireland")&&Readybtn.isShowing()==false){
            irelandTA.setVisible(true);
            irelandLbl.setVisible(true);
            noticeTA.setVisible(true);
        }
        else{
            irelandTA.setVisible(false);
            irelandLbl.setVisible(false);
            noticeTA.setVisible(false);
        }
    }//GEN-LAST:event_irelandBtnMouseEntered

    private void irelandBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_irelandBtnMouseExited
        // TODO add your handling code here:
        irelandTA.setVisible(false);
        irelandLbl.setVisible(false);
        noticeTA.setVisible(false);
    }//GEN-LAST:event_irelandBtnMouseExited

    private void icelandBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icelandBtnMouseEntered
        // TODO add your handling code here:
         if(icelandBtn.getText().contains("Iceland")&&Readybtn.isShowing()==false){
        icelandTA.setVisible(true);
        icelandLbl.setVisible(true);
        noticeTA.setVisible(true);
         }
         else{
            icelandTA.setVisible(false);
            icelandLbl.setVisible(false);
            noticeTA.setVisible(false);
         }
    }//GEN-LAST:event_icelandBtnMouseEntered

    private void icelandBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icelandBtnMouseExited
        // TODO add your handling code here:
       
        icelandTA.setVisible(false);
        icelandLbl.setVisible(false);
        noticeTA.setVisible(false);
        
        
    }//GEN-LAST:event_icelandBtnMouseExited
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EuropeTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EuropeTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EuropeTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EuropeTutorialGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EuropeTutorialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton Readybtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton franceBtn;
    private javax.swing.JButton germanyBtn;
    private javax.swing.JButton icelandBtn;
    private javax.swing.JLabel icelandLbl;
    private javax.swing.JTextArea icelandTA;
    private javax.swing.JButton irelandBtn;
    private javax.swing.JLabel irelandLbl;
    private javax.swing.JTextArea irelandTA;
    private javax.swing.JButton italyBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel map;
    private javax.swing.JButton nextBtn;
    private javax.swing.JTextArea noticeTA;
    private javax.swing.JButton polandBtn;
    private javax.swing.JLabel polandLbl;
    private javax.swing.JTextArea polandTA;
    private javax.swing.JLabel questLbl;
    private javax.swing.JLabel reminderLbl;
    private javax.swing.JButton russiaBtn;
    private javax.swing.JLabel russiaLbl;
    private javax.swing.JTextArea russiaTA;
    private javax.swing.JButton scandanavianBtn;
    private javax.swing.JButton spainBtn;
    private javax.swing.JLabel spainLbl;
    private javax.swing.JTextArea spainTA;
    private javax.swing.JButton turkeyBtn;
    // End of variables declaration//GEN-END:variables
}
