/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package continentalconquest;

import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13332576
 */
public class LeaderGUI extends javax.swing.JFrame {
ContinentalConquest q;
jdbcTest t;
String name;
int age;

    /**
     * Creates new form LeaderGUI
     */
    public LeaderGUI() throws MalformedURLException {
        initComponents();
        q = new ContinentalConquest();
        t = new jdbcTest();
        name = "";
        age = 0;
                 try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select * from player order by score desc";
            ResultSet rs = st.executeQuery(find);
            while(rs.next()){
                txtArea.append("\nName: "+rs.getString("name"));
                
                txtArea.append("\nScore: "+rs.getInt("score")+"\n\n");
            }
            
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SoundBtn = new javax.swing.JToggleButton();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        searchBtn = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        CloseB = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(608, 555));
        getContentPane().setLayout(null);

        SoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Sound2.png"))); // NOI18N
        SoundBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SoundBtn.setBorderPainted(false);
        SoundBtn.setContentAreaFilled(false);
        SoundBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/SoundOff.png"))); // NOI18N
        SoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SoundBtn);
        SoundBtn.setBounds(10, 500, 83, 37);

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/back.png"))); // NOI18N
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(0, 30, 180, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/leaderBoards.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(222, 11, 208, 65);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(135, 78, 166, 0);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(135, 96, 300, 340);

        searchBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorderPainted(false);
        searchBtn.setContentAreaFilled(false);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(460, 200, 110, 50);

        searchTF.setText("Enter a name...");
        getContentPane().add(searchTF);
        searchTF.setBounds(453, 172, 129, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(598, 4, 20, 20);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 4, 20, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        StartGUI start = null;
    try {
        start = new StartGUI();
    } catch (MalformedURLException ex) {
        Logger.getLogger(LeaderGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundBtnActionPerformed
        // TODO add your handling code here:
        if(q.isPlaying()==true){
            q.stop();
        }
        else{
            q.start();
        }
        //q.stop();
    }//GEN-LAST:event_SoundBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        name = searchTF.getText();
         try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select * from player where name = '"+name+"'";
            ResultSet rs = st.executeQuery(find);
            while(rs.next()){
                txtArea.append("\nName: "+rs.getString("name"));
               
                txtArea.append("\nScore: "+rs.getInt("score")+"\n\n");
            }
            
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }    
        
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LeaderGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(LeaderGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JToggleButton SoundBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTF;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
