/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13332576
 */
public class OceaniaGUI extends javax.swing.JFrame {

    /**
     * Creates new form OceaniaGUI
     */
    public OceaniaGUI() {
        initComponents();
        String select;
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        australiaBtn = new javax.swing.JButton();
        newzBtn = new javax.swing.JButton();
        map = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        titleLbl.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        titleLbl.setText("Oceania");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(440, 110, 150, 90);

        backBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        backBtn.setText("Back to Menu");
        backBtn.setContentAreaFilled(false);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(-10, 70, 170, 60);

        australiaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        australiaBtn.setText("Australia");
        australiaBtn.setContentAreaFilled(false);
        australiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                australiaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(australiaBtn);
        australiaBtn.setBounds(40, 70, 390, 410);

        newzBtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        newzBtn.setText("New Zealand");
        newzBtn.setContentAreaFilled(false);
        newzBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newzBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newzBtn);
        newzBtn.setBounds(450, 350, 160, 190);

        map.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/tutmapAus.png"))); // NOI18N
        getContentPane().add(map);
        map.setBounds(0, 26, 620, 510);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void australiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_australiaBtnActionPerformed
        // TODO add your handling code here:
     AustraliaGUI newGUI = new AustraliaGUI();
     newGUI.setVisible(true);
     this.dispose();

    }//GEN-LAST:event_australiaBtnActionPerformed

    private void newzBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newzBtnActionPerformed
        // TODO add your handling code here:
     NewzGUI newGUI = new NewzGUI();
     newGUI.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_newzBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        tempGUI temp = new tempGUI();
        temp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OceaniaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OceaniaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OceaniaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OceaniaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* TitleLblnd display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OceaniaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton australiaBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel map;
    private javax.swing.JButton newzBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
