package continentalconquest;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x13508623
 */
public class PeruQ extends javax.swing.JFrame {
    String question;
    int count;
    int count2;
    private static final String VOICENAME = "kevin16";
    /**
     * Creates new form USA
     */
    public PeruQ() {
        initComponents();
        question = "";
        count=0;
        count2=0;
         yBtn.setVisible(false);
        nBtn.setVisible(false);
        
try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = QLbl.getText();
                QLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    AnsBtn1.setText(arr[0]);
                    AnsBtn2.setText(arr[1]);
                    AnsBtn3.setText(arr[2]);
                    AnsBtn4.setText(arr[3]);
                }

            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }        
                
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QPanel = new javax.swing.JPanel();
        QLbl = new javax.swing.JLabel();
        voiceBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        scoreLbl = new javax.swing.JLabel();
        countryLbl = new javax.swing.JLabel();
        AnsBtn1 = new javax.swing.JButton();
        AnsBtn2 = new javax.swing.JButton();
        AnsBtn3 = new javax.swing.JButton();
        AnsBtn4 = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        ImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 542));
        getContentPane().setLayout(null);

        QPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout QPanelLayout = new javax.swing.GroupLayout(QPanel);
        QPanel.setLayout(QPanelLayout);
        QPanelLayout.setHorizontalGroup(
            QPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QPanelLayout.createSequentialGroup()
                .addGap(0, 121, Short.MAX_VALUE)
                .addComponent(QLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        QPanelLayout.setVerticalGroup(
            QPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QPanelLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(QLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(QPanel);
        QPanel.setBounds(80, 50, 450, 150);

        voiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/voice button.png"))); // NOI18N
        voiceBtn.setContentAreaFilled(false);
        voiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voiceBtn);
        voiceBtn.setBounds(520, 10, 80, 70);

        nBtn.setBackground(new java.awt.Color(255, 255, 255));
        nBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nBtn.setText("No");
        nBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nBtn.setContentAreaFilled(false);
        nBtn.setOpaque(true);
        nBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nBtn);
        nBtn.setBounds(340, 300, 210, 70);

        yBtn.setBackground(new java.awt.Color(255, 255, 255));
        yBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        yBtn.setText("Yes");
        yBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        yBtn.setContentAreaFilled(false);
        yBtn.setOpaque(true);
        yBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yBtnActionPerformed(evt);
            }
        });
        getContentPane().add(yBtn);
        yBtn.setBounds(110, 300, 210, 70);

        scoreLbl.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        getContentPane().add(scoreLbl);
        scoreLbl.setBounds(100, 430, 440, 30);

        countryLbl.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        getContentPane().add(countryLbl);
        countryLbl.setBounds(130, 20, 360, 20);

        AnsBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(AnsBtn1);
        AnsBtn1.setBounds(80, 250, 200, 50);

        AnsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(AnsBtn2);
        AnsBtn2.setBounds(330, 250, 200, 50);

        AnsBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(AnsBtn3);
        AnsBtn3.setBounds(330, 340, 200, 50);

        AnsBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(AnsBtn4);
        AnsBtn4.setBounds(80, 340, 200, 50);

        BackBtn.setText("BACK");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(260, 490, 73, 23);

        ImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/PeruFlag.png"))); // NOI18N
        getContentPane().add(ImgLbl);
        ImgLbl.setBounds(0, 0, 620, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        AmericasGUI start =  new AmericasGUI();
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void AnsBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsBtn4ActionPerformed
        // TODO add your handling code here:
                       if(count2==10){
                    scoreLbl.setVisible(true);
                    AnsBtn1.setVisible(false);
                    AnsBtn2.setVisible(false);
                    AnsBtn3.setVisible(false);
                    AnsBtn4.setVisible(false);
                    if(count<10){
                        countryLbl.setText("Retreat!");
                        QLbl.setText("");
                        scoreLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        countryLbl.setText("Peru conquered");
                        QLbl.setText("");
                        scoreLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
        }
  try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = QLbl.getText();
                QLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    AnsBtn1.setText(arr[0]);
                    AnsBtn2.setText(arr[1]);
                    AnsBtn3.setText(arr[2]);
                    AnsBtn4.setText(arr[3]);
                }
                     if(arr[3].equals(rs.getString("answer"))){
                                Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    scoreLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     scoreLbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }      
    }//GEN-LAST:event_AnsBtn4ActionPerformed

    private void AnsBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsBtn1ActionPerformed
        // TODO add your handling code here:
                        if(count2==10){
                    scoreLbl.setVisible(true);
                    AnsBtn1.setVisible(false);
                    AnsBtn2.setVisible(false);
                    AnsBtn3.setVisible(false);
                    AnsBtn4.setVisible(false);
                    if(count<10){
                        countryLbl.setText("Retreat!");
                        QLbl.setText("");
                        scoreLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        countryLbl.setText("Peru conquered");
                        QLbl.setText("");
                        scoreLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
        }
  try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = QLbl.getText();
                QLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    AnsBtn1.setText(arr[0]);
                    AnsBtn2.setText(arr[1]);
                    AnsBtn3.setText(arr[2]);
                    AnsBtn4.setText(arr[3]);
                }
                     if(arr[0].equals(rs.getString("answer"))){
                                 Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    scoreLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     scoreLbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }      
    }//GEN-LAST:event_AnsBtn1ActionPerformed

    private void AnsBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsBtn3ActionPerformed
        // TODO add your handling code here:
                        if(count2==10){
                    scoreLbl.setVisible(true);
                    AnsBtn1.setVisible(false);
                    AnsBtn2.setVisible(false);
                    AnsBtn3.setVisible(false);
                    AnsBtn4.setVisible(false);
                    if(count<10){
                        countryLbl.setText("Retreat!");
                        QLbl.setText("");
                        scoreLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        countryLbl.setText("Peru conquered");
                        QLbl.setText("");
                        scoreLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
        }
  try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = QLbl.getText();
                QLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    AnsBtn1.setText(arr[0]);
                    AnsBtn2.setText(arr[1]);
                    AnsBtn3.setText(arr[2]);
                    AnsBtn4.setText(arr[3]);
                }
                     if(arr[2].equals(rs.getString("answer"))){
                                  Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    scoreLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     scoreLbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }      
    }//GEN-LAST:event_AnsBtn3ActionPerformed

    private void AnsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsBtn2ActionPerformed
        // TODO add your handling code here:
                        if(count2==10){
                    scoreLbl.setVisible(true);
                    AnsBtn1.setVisible(false);
                    AnsBtn2.setVisible(false);
                    AnsBtn3.setVisible(false);
                    AnsBtn4.setVisible(false);
                    if(count<10){
                        countryLbl.setText("Retreat!");
                        QLbl.setText("");
                        scoreLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==10){
                        countryLbl.setText("Peru conquered");
                        QLbl.setText("");
                        scoreLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
        }
    try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = QLbl.getText();
                QLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    AnsBtn1.setText(arr[0]);
                    AnsBtn2.setText(arr[1]);
                    AnsBtn3.setText(arr[2]);
                    AnsBtn4.setText(arr[3]);
                }
                     if(arr[1].equals(rs.getString("answer"))){
                                 Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    scoreLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     scoreLbl.setText("AHH, your last answer was incorrect.");
                 }
            }
            

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }      
    }//GEN-LAST:event_AnsBtn2ActionPerformed

    private void nBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBtnActionPerformed
        // TODO add your handling code here:
        EuropeGUI europe =null;
        try {
            europe = new EuropeGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(IrelandGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        europe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nBtnActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);

            Statement st = (Statement) conn.createStatement();

            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Question set q_sel = 'N';";
            st.executeUpdate(update);
            /* */
            try {
                countryLbl.setText("Peru Quiz");
                AnsBtn1.setVisible(true);
                AnsBtn2.setVisible(true);
                AnsBtn3.setVisible(true);
                AnsBtn4.setVisible(true);
                count2=0;
                count=0;
                QLbl.setVisible(true);
                scoreLbl.setVisible(false);
                yBtn.setVisible(false);
                nBtn.setVisible(false);
                String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'peru' and q_sel = 'N' order by rand() limit 1;";
                ResultSet rs = st.executeQuery(find);

                /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

                while(rs.next()){
                    question = QLbl.getText();
                    QLbl.setText("\n"+rs.getString("quest"));
                    Statement st2 = conn.createStatement();
                    st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                    String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                    String [] arr = solutionArray;
                    Random rgen = new Random();
                    int N = arr.length;
                    /*
                    * fisher yates shuffle
                    *
                    * 9/3/2015
                    *
                    * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                    * @author sean trant 13332576
                    */

                    for (int i = 0; i < N; i++) {
                        // choose index uniformly in [i, N-1]
                        int r = i + (int) (Math.random() * (N - i));
                        Object swap = arr[r];
                        arr[r] = arr[i];
                        arr[i] = (String)swap;

                        AnsBtn1.setText(arr[0]);
                        AnsBtn2.setText(arr[1]);
                        AnsBtn3.setText(arr[2]);
                        AnsBtn4.setText(arr[3]);
                    }

                }

            } catch (Exception ex) {
                System.out.println("AGGHHHH!!!!!");
            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }
    }//GEN-LAST:event_yBtnActionPerformed

    private void voiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceBtnActionPerformed
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        voice.allocate();
        try{
            voice.speak(QLbl.getText());
            voice.speak("Answer, one");
            voice.speak(AnsBtn1.getText());
            voice.speak("Answer, two");
            voice.speak(AnsBtn2.getText());
            voice.speak("Answer, three");
            voice.speak(AnsBtn3.getText());
            voice.speak("Answer, four");
            voice.speak(AnsBtn4.getText());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_voiceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeruQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeruQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeruQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeruQ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeruQ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnsBtn1;
    private javax.swing.JButton AnsBtn2;
    private javax.swing.JButton AnsBtn3;
    private javax.swing.JButton AnsBtn4;
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel ImgLbl;
    private javax.swing.JLabel QLbl;
    private javax.swing.JPanel QPanel;
    private javax.swing.JLabel countryLbl;
    private javax.swing.JButton nBtn;
    private javax.swing.JLabel scoreLbl;
    private javax.swing.JButton voiceBtn;
    private javax.swing.JButton yBtn;
    // End of variables declaration//GEN-END:variables
}
