/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author x13332576
 */
public class SelectGUI extends javax.swing.JFrame {
    ContinentalConquest q; 
    
  private Connection conn;
  
    ArrayList<Player> list;
    String name;
    String insert;
    int age;
    String avatar;
    jdbcTest t;
    /**
     * Creates new form SelectGUI
     */
    public SelectGUI() throws MalformedURLException {
        initComponents();
        list = new ArrayList<Player>();
        q = new ContinentalConquest();
        name = "";
        avatar = "";
        age = 0;
        char2.setVisible(false);
        char3.setVisible(false);
        t = new jdbcTest();
     //  CustomCursor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }
    
    
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectionGroup = new javax.swing.ButtonGroup();
        NameLbl = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        ageLbl = new javax.swing.JLabel();
        ageTF = new javax.swing.JTextField();
        beginBtn = new javax.swing.JButton();
        char1 = new javax.swing.JLabel();
        char2 = new javax.swing.JLabel();
        char3 = new javax.swing.JLabel();
        charBtn1 = new javax.swing.JRadioButton();
        charBtn2 = new javax.swing.JRadioButton();
        charBtn3 = new javax.swing.JRadioButton();
        SoundBtn = new javax.swing.JToggleButton();
        BackBtn = new javax.swing.JButton();
        CloseB = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        BackgroundLbl = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        NameLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/name.png"))); // NOI18N
        getContentPane().add(NameLbl);
        NameLbl.setBounds(130, 30, 90, 30);
        getContentPane().add(nameTF);
        nameTF.setBounds(220, 40, 170, 20);

        ageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/age.png"))); // NOI18N
        getContentPane().add(ageLbl);
        ageLbl.setBounds(130, 70, 60, 30);

        ageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTFActionPerformed(evt);
            }
        });
        getContentPane().add(ageTF);
        ageTF.setBounds(220, 80, 170, 20);

        beginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Begin.png"))); // NOI18N
        beginBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        beginBtn.setContentAreaFilled(false);
        beginBtn.setOpaque(true);
        beginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(beginBtn);
        beginBtn.setBounds(180, 440, 260, 73);

        char1.setBackground(null);
        char1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/character.png"))); // NOI18N
        getContentPane().add(char1);
        char1.setBounds(190, 130, 224, 270);

        char2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/character2.png"))); // NOI18N
        getContentPane().add(char2);
        char2.setBounds(190, 180, 190, 170);

        char3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/character3.png"))); // NOI18N
        getContentPane().add(char3);
        char3.setBounds(200, 130, 190, 260);

        selectionGroup.add(charBtn1);
        charBtn1.setContentAreaFilled(false);
        charBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/dorian.png"))); // NOI18N
        charBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(charBtn1);
        charBtn1.setBounds(440, 190, 130, 30);

        selectionGroup.add(charBtn2);
        charBtn2.setContentAreaFilled(false);
        charBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/jorian.png"))); // NOI18N
        charBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(charBtn2);
        charBtn2.setBounds(450, 230, 110, 35);

        selectionGroup.add(charBtn3);
        charBtn3.setContentAreaFilled(false);
        charBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/torian.png"))); // NOI18N
        charBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(charBtn3);
        charBtn3.setBounds(450, 270, 111, 30);

        SoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Sound2.png"))); // NOI18N
        SoundBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        SoundBtn.setBorderPainted(false);
        SoundBtn.setContentAreaFilled(false);
        SoundBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/SoundOff.png"))); // NOI18N
        SoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SoundBtn);
        SoundBtn.setBounds(10, 450, 83, 40);

        BackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/back.png"))); // NOI18N
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(0, 210, 180, 40);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(598, 4, 20, 20);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 4, 20, 20);

        BackgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/worldMap1.gif"))); // NOI18N
        BackgroundLbl.setToolTipText("");
        getContentPane().add(BackgroundLbl);
        BackgroundLbl.setBounds(0, 0, 620, 540);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void beginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beginBtnActionPerformed
        // TODO add your handling code here:
         name = nameTF.getText();
        age = Integer.parseInt(ageTF.getText());
        //avatar = selectionGroup.getSelection();
        Player p = new Player(name,avatar,age);
        
        p.setName(nameTF.getText());
        p.setAge(Integer.parseInt(ageTF.getText()));

   
            
        list.add(p);  
        
             try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            insert = "insert into Player values('"+name+"','"+age+"','Y',0)";
            st.executeUpdate(insert);
            /* */
            
            String query = "SELECT * FROM Player";
             st = conn.createStatement();
             ResultSet rs = st.executeQuery(query);
             t.printResultSet(rs);

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        tempGUI newGUI = new tempGUI();
        newGUI.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_beginBtnActionPerformed

    private void ageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTFActionPerformed

    private void SoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundBtnActionPerformed
        // TODO add your handling code here:
        if(q.isPlaying()==true){
            q.stop();
        }
        else{
            q.start();
        }
        //q.stop();
    }//GEN-LAST:event_SoundBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        StartGUI start = null;
        try {
            start = new StartGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(SelectGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void charBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charBtn1ActionPerformed
        // TODO add your handling code here:
        char1.setVisible(true);
        char2.setVisible(false);
        char3.setVisible(false);
    }//GEN-LAST:event_charBtn1ActionPerformed

    private void charBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charBtn2ActionPerformed
        // TODO add your handling code here:
        char1.setVisible(false);
        char2.setVisible(true);
        char3.setVisible(false);
    }//GEN-LAST:event_charBtn2ActionPerformed

    private void charBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charBtn3ActionPerformed
        // TODO add your handling code here:
        char1.setVisible(false);
        char2.setVisible(false);
        char3.setVisible(true);
    }//GEN-LAST:event_charBtn3ActionPerformed

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);

    }//GEN-LAST:event_MinBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SelectGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(SelectGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundLbl;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JLabel NameLbl;
    private javax.swing.JToggleButton SoundBtn;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JTextField ageTF;
    private javax.swing.JButton beginBtn;
    private javax.swing.JLabel char1;
    private javax.swing.JLabel char2;
    private javax.swing.JLabel char3;
    private javax.swing.JRadioButton charBtn1;
    private javax.swing.JRadioButton charBtn2;
    private javax.swing.JRadioButton charBtn3;
    private javax.swing.JTextField nameTF;
    private javax.swing.ButtonGroup selectionGroup;
    // End of variables declaration//GEN-END:variables
}
