/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.net.MalformedURLException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author x13564737
 */
public class SpainGUI extends javax.swing.JFrame {
 //String insert;
    String question;
    int count;
    int count2;
    private static final String VOICENAME = "kevin16";
   // jdbcTest t; 
    /**
     * Creates new form SpainGUI
     */
    public SpainGUI() {
        initComponents();
        // insert = " ";
        question = " ";
        count = 0;
        count2 = 0;
        yBtn.setVisible(false);
        nBtn.setVisible(false);
      try {

            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            Statement st = (Statement) conn.createStatement();
            String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'spain' and q_sel = 'N' order by rand() limit 1;";
            ResultSet rs = st.executeQuery(find);

            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

            while(rs.next()){
                question = questionLbl.getText();
                questionLbl.setText("\n"+rs.getString("quest"));
                Statement st2 = conn.createStatement();
                st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

                String [] arr = solutionArray;
                Random rgen = new Random();
                int N = arr.length;
                /*
                * fisher yates shuffle
                *
                * 9/3/2015
                *
                * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                * @author sean trant 13332576
                */

                for (int i = 0; i < N; i++) {
                    // choose index uniformly in [i, N-1]
                    int r = i + (int) (Math.random() * (N - i));
                    Object swap = arr[r];
                    arr[r] = arr[i];
                    arr[i] = (String)swap;

                    answerBtn1.setText(arr[0]);
                    answerBtn2.setText(arr[1]);
                    answerBtn3.setText(arr[2]);
                    answerBtn4.setText(arr[3]);
                }

            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }      
       //t = new jdbcTest();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        voiceBtn = new javax.swing.JButton();
        yBtn = new javax.swing.JButton();
        nBtn = new javax.swing.JButton();
        correctLbl = new javax.swing.JLabel();
        answerBtn4 = new javax.swing.JButton();
        answerBtn3 = new javax.swing.JButton();
        answerBtn1 = new javax.swing.JButton();
        answerBtn2 = new javax.swing.JButton();
        questionLbl = new javax.swing.JLabel();
        spainLbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        flagLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 570));
        setPreferredSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        voiceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/voice button.png"))); // NOI18N
        voiceBtn.setContentAreaFilled(false);
        voiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voiceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(voiceBtn);
        voiceBtn.setBounds(520, 10, 80, 70);

        yBtn.setBackground(new java.awt.Color(255, 255, 255));
        yBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        yBtn.setText("Yes");
        yBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        yBtn.setContentAreaFilled(false);
        yBtn.setOpaque(true);
        yBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yBtnActionPerformed(evt);
            }
        });
        getContentPane().add(yBtn);
        yBtn.setBounds(110, 300, 210, 70);

        nBtn.setBackground(new java.awt.Color(255, 255, 255));
        nBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        nBtn.setText("No");
        nBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        nBtn.setContentAreaFilled(false);
        nBtn.setOpaque(true);
        nBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBtnActionPerformed(evt);
            }
        });
        getContentPane().add(nBtn);
        nBtn.setBounds(340, 300, 210, 70);

        correctLbl.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        getContentPane().add(correctLbl);
        correctLbl.setBounds(50, 490, 520, 40);

        answerBtn4.setBackground(new java.awt.Color(255, 255, 255));
        answerBtn4.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        answerBtn4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerBtn4.setContentAreaFilled(false);
        answerBtn4.setOpaque(true);
        answerBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBtn4);
        answerBtn4.setBounds(390, 370, 190, 70);

        answerBtn3.setBackground(new java.awt.Color(255, 255, 255));
        answerBtn3.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        answerBtn3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerBtn3.setContentAreaFilled(false);
        answerBtn3.setOpaque(true);
        answerBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBtn3);
        answerBtn3.setBounds(90, 370, 210, 70);

        answerBtn1.setBackground(new java.awt.Color(255, 255, 255));
        answerBtn1.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        answerBtn1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerBtn1.setContentAreaFilled(false);
        answerBtn1.setOpaque(true);
        answerBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBtn1);
        answerBtn1.setBounds(90, 240, 210, 70);

        answerBtn2.setBackground(new java.awt.Color(255, 255, 255));
        answerBtn2.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        answerBtn2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        answerBtn2.setContentAreaFilled(false);
        answerBtn2.setOpaque(true);
        answerBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(answerBtn2);
        answerBtn2.setBounds(390, 240, 190, 70);

        questionLbl.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        getContentPane().add(questionLbl);
        questionLbl.setBounds(40, 170, 560, 40);

        spainLbl.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        spainLbl.setForeground(new java.awt.Color(255, 0, 0));
        spainLbl.setText("Spain Quiz");
        getContentPane().add(spainLbl);
        spainLbl.setBounds(190, 80, 190, 40);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(20, 40, 69, 23);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(0, 10, 620, 60);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 78, 620, 411);

        jSeparator2.setPreferredSize(new java.awt.Dimension(62, 2));
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 470, 620, 60);

        flagLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/spainflag.jpg"))); // NOI18N
        flagLbl.setText("jLabel1");
        getContentPane().add(flagLbl);
        flagLbl.setBounds(-6, -6, 630, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        EuropeGUI europe =null;
        try {
            europe = new EuropeGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(SpainGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        europe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void answerBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtn2ActionPerformed
        // TODO add your handling code here:
         if(count2==4){
                    correctLbl.setVisible(true);
                    answerBtn1.setVisible(false);
                    answerBtn2.setVisible(false);
                    answerBtn3.setVisible(false);
                    answerBtn4.setVisible(false);
                    if(count<4){
                        spainLbl.setText("Retreat!");
                        questionLbl.setText("");
                        correctLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==4){
                        spainLbl.setText("Spain conquered");
                        questionLbl.setText("");
                        correctLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
        try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'spain' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionLbl.getText();
questionLbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answerBtn1.setText(arr[0]);
answerBtn2.setText(arr[1]);
answerBtn3.setText(arr[2]);
answerBtn4.setText(arr[3]); 
}

if(arr[1].equals(rs.getString("answer"))){
     Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    correctLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     correctLbl.setText("AHH, your last answer was incorrect.");
                 }
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answerBtn2ActionPerformed

    private void answerBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtn3ActionPerformed
        // TODO add your handling code here:
               if(count2==4){
                    correctLbl.setVisible(true);
                    answerBtn1.setVisible(false);
                    answerBtn2.setVisible(false);
                    answerBtn3.setVisible(false);
                    answerBtn4.setVisible(false);
                    if(count<4){
                        spainLbl.setText("Retreat!");
                        questionLbl.setText("");
                        correctLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==4){
                        spainLbl.setText("Spain conquered");
                        questionLbl.setText("");
                        correctLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
        try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'spain' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionLbl.getText();
questionLbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answerBtn1.setText(arr[0]);
answerBtn2.setText(arr[1]);
answerBtn3.setText(arr[2]);
answerBtn4.setText(arr[3]); 
}

if(arr[2].equals(rs.getString("answer"))){
     Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    correctLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     correctLbl.setText("AHH, your last answer was incorrect.");
                 }
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answerBtn3ActionPerformed

    private void answerBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtn1ActionPerformed
        // TODO add your handling code here:
               if(count2==4){
                    correctLbl.setVisible(true);
                    answerBtn1.setVisible(false);
                    answerBtn2.setVisible(false);
                    answerBtn3.setVisible(false);
                    answerBtn4.setVisible(false);
                    if(count<4){
                        spainLbl.setText("Retreat!");
                        questionLbl.setText("");
                        correctLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==4){
                        spainLbl.setText("Spain conquered");
                        questionLbl.setText("");
                        correctLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
        try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'spain' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionLbl.getText();
questionLbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answerBtn1.setText(arr[0]);
answerBtn2.setText(arr[1]);
answerBtn3.setText(arr[2]);
answerBtn4.setText(arr[3]); 
}

if(arr[0].equals(rs.getString("answer"))){
     Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    correctLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     correctLbl.setText("AHH, your last answer was incorrect.");
                 }
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answerBtn1ActionPerformed

    private void answerBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerBtn4ActionPerformed
        // TODO add your handling code here:
               if(count2==4){
                    correctLbl.setVisible(true);
                    answerBtn1.setVisible(false);
                    answerBtn2.setVisible(false);
                    answerBtn3.setVisible(false);
                    answerBtn4.setVisible(false);
                    if(count<4){
                        spainLbl.setText("Retreat!");
                        questionLbl.setText("");
                        correctLbl.setText("You got "+count+" questions correct. Don't worry, try again?");
                        yBtn.setVisible(true);
                        nBtn.setVisible(true);
                    }
                    else if(count==4){
                        spainLbl.setText("Spain conquered");
                        questionLbl.setText("");
                        correctLbl.setText("You got all"+count+" questions correct.Well done!");
                    }
                    
                 } 
        try {

Class.forName("com.mysql.jdbc.Driver");
String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
Connection conn = DriverManager.getConnection(connectionUrl);
Statement st = (Statement) conn.createStatement();
String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'spain' and q_sel = 'N' order by rand() limit 1;"; 
ResultSet rs = st.executeQuery(find);

/* https://www.youtube.com/watch?v=MY4FavUyFNQ */ 

while(rs.next()){
question = questionLbl.getText();
questionLbl.setText("\n"+rs.getString("quest")); 
Statement st2 = conn.createStatement();
st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};

String [] arr = solutionArray;
Random rgen = new Random();
int N = arr.length;
/*
* fisher yates shuffle
*
* 9/3/2015
*
* @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
* @author sean trant 13332576
*/ 
for (int i = 0; i < N; i++) {
// choose index uniformly in [i, N-1]
int r = i + (int) (Math.random() * (N - i));
Object swap = arr[r];
arr[r] = arr[i];
arr[i] = (String)swap;

answerBtn1.setText(arr[0]);
answerBtn2.setText(arr[1]);
answerBtn3.setText(arr[2]);
answerBtn4.setText(arr[3]); 
}

if(arr[3].equals(rs.getString("answer"))){
     Statement st3 = (Statement) conn.createStatement();
                    st3.executeUpdate("update Player set score = score+1 where p_sel='Y'");
                    count++;
                    correctLbl.setText("Your last answer was correct!");
                    } 
                 else{
                     correctLbl.setText("AHH, your last answer was incorrect.");
                 }
}

} catch (Exception ex) {
System.out.println("AGGHHHH!!!!!"); 
}
    }//GEN-LAST:event_answerBtn4ActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);

            Statement st = (Statement) conn.createStatement();

            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Question set q_sel = 'N';";
            st.executeUpdate(update);
            /* */
            try {
                spainLbl.setText("Ireland Quiz");
                answerBtn1.setVisible(true);
                answerBtn2.setVisible(true);
                answerBtn3.setVisible(true);
                answerBtn4.setVisible(true);
                count2=0;
                count=0;
                questionLbl.setVisible(true);
                correctLbl.setVisible(false);
                yBtn.setVisible(false);
                nBtn.setVisible(false);
                String find = "select quest,answer,wrongAns,wrongAns2,wrongAns3,q_sel from Question where country = 'ireland' and q_sel = 'N' order by rand() limit 1;";
                ResultSet rs = st.executeQuery(find);

                /* https://www.youtube.com/watch?v=MY4FavUyFNQ */

                while(rs.next()){
                    question = questionLbl.getText();
                    questionLbl.setText("\n"+rs.getString("quest"));
                    Statement st2 = conn.createStatement();
                    st2.executeUpdate("update Question set q_sel = 'Y' where quest = '"+rs.getString("quest")+"'");

                    String[] solutionArray = {rs.getString("answer"),rs.getString("wrongAns"),rs.getString("wrongAns2"),rs.getString("wrongAns3")};
                    
                    String []arr = solutionArray;
                    Random rgen = new Random();
                    int N = arr.length;
                    /*
                    * fisher yates shuffle
                    *
                    * 9/3/2015
                    *
                    * @reference http://algs4.cs.princeton.edu/11model/Knuth.java.html
                    * @author sean trant 13332576
                    */

                    for (int i = 0; i < N; i++) {
                        // choose index uniformly in [i, N-1]
                        int r = i + (int) (Math.random() * (N - i));
                        Object swap = arr[r];
                        arr[r] = arr[i];
                        arr[i] = (String)swap;

                        answerBtn1.setText(arr[0]);
                        answerBtn2.setText(arr[1]);
                        answerBtn3.setText(arr[2]);
                        answerBtn4.setText(arr[3]);
                    }

                }

            } catch (Exception ex) {
                System.out.println("AGGHHHH!!!!!");
            }

        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");
        }
    }//GEN-LAST:event_yBtnActionPerformed

    private void nBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBtnActionPerformed
        // TODO add your handling code here:
        EuropeGUI europe =null;
        try {
            europe = new EuropeGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(IrelandGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        europe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nBtnActionPerformed

    private void voiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voiceBtnActionPerformed
        // TODO add your handling code here:
        Voice voice;
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice(VOICENAME);
        voice.allocate();
        try{
            voice.speak(questionLbl.getText());
            voice.speak("Answer, one");
            voice.speak(answerBtn1.getText());
            voice.speak("Answer, two");
            voice.speak(answerBtn2.getText());
            voice.speak("Answer, three");
            voice.speak(answerBtn3.getText());
            voice.speak("Answer, four");
            voice.speak(answerBtn4.getText());
        }
        catch(Exception e){

        }
    }//GEN-LAST:event_voiceBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton answerBtn1;
    private javax.swing.JButton answerBtn2;
    private javax.swing.JButton answerBtn3;
    private javax.swing.JButton answerBtn4;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel correctLbl;
    private javax.swing.JLabel flagLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton nBtn;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JLabel spainLbl;
    private javax.swing.JButton voiceBtn;
    private javax.swing.JButton yBtn;
    // End of variables declaration//GEN-END:variables
}
