/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;


import java.awt.Cursor;
import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author x13332576
 */
public class StartGUI extends javax.swing.JFrame {

    ContinentalConquest q; 
    
    /**
     * Creates new form SoundTestGUI
     */
    public StartGUI() throws MalformedURLException {
        initComponents();
        adminBtn.setVisible(false);
        passwordTF.setVisible(false);
       //CustomCursor(); 
        
        q = new ContinentalConquest();
    try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set p_sel = 'N';";
            st.executeUpdate(update);
            String update2 = "update Continent set locked ='Yes' where name = 'America' or name = 'Asia' or name = 'Australia' or name = 'Africa';";
            st.executeUpdate(update2);
            /* */


        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }          
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartBtn = new javax.swing.JButton();
        hideBtn = new javax.swing.JButton();
        IconLbl = new javax.swing.JLabel();
        LeaderBtn = new javax.swing.JButton();
        SoundBtn = new javax.swing.JToggleButton();
        adminBtn = new javax.swing.JButton();
        passwordTF = new javax.swing.JTextField();
        CloseB = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        StartBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ButtonDefault.png"))); // NOI18N
        StartBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        StartBtn.setBorderPainted(false);
        StartBtn.setContentAreaFilled(false);
        StartBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StartBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StartBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                StartBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                StartBtnMouseReleased(evt);
            }
        });
        StartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtnActionPerformed(evt);
            }
        });
        getContentPane().add(StartBtn);
        StartBtn.setBounds(202, 247, 215, 73);

        hideBtn.setBorderPainted(false);
        hideBtn.setContentAreaFilled(false);
        hideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hideBtn);
        hideBtn.setBounds(10, 33, 170, 120);

        IconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/ICON.png"))); // NOI18N
        getContentPane().add(IconLbl);
        IconLbl.setBounds(200, 30, 215, 200);

        LeaderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Buttonleader.png"))); // NOI18N
        LeaderBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        LeaderBtn.setBorderPainted(false);
        LeaderBtn.setContentAreaFilled(false);
        LeaderBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LeaderBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LeaderBtnMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LeaderBtnMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LeaderBtnMouseReleased(evt);
            }
        });
        LeaderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeaderBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LeaderBtn);
        LeaderBtn.setBounds(202, 372, 221, 73);

        SoundBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/Sound2.png"))); // NOI18N
        SoundBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 10, true));
        SoundBtn.setBorderPainted(false);
        SoundBtn.setContentAreaFilled(false);
        SoundBtn.setMinimumSize(new java.awt.Dimension(620, 540));
        SoundBtn.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/SoundOff.png"))); // NOI18N
        SoundBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SoundBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SoundBtn);
        SoundBtn.setBounds(20, 440, 95, 62);

        adminBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        adminBtn.setForeground(new java.awt.Color(0, 0, 153));
        adminBtn.setText("Admin");
        adminBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        adminBtn.setContentAreaFilled(false);
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminBtn);
        adminBtn.setBounds(30, 80, 110, 30);

        passwordTF.setText("Enter password...");
        getContentPane().add(passwordTF);
        passwordTF.setBounds(30, 50, 130, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(598, 4, 20, 20);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 4, 20, 20);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SoundBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SoundBtnActionPerformed
        // TODO add your handling code here:
        if(q.isPlaying()==true){
            q.stop();
        }
        else{
            q.start();
        }
        //q.stop();
    }//GEN-LAST:event_SoundBtnActionPerformed

    private void StartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtnActionPerformed
        // TODO add your handling code here:
        SelectGUI select = null;
        try {
            select = new SelectGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        select.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_StartBtnActionPerformed

    private void LeaderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeaderBtnActionPerformed
        // TODO add your handling code here:
        LeaderGUI leader = null;
        try {
            leader = new LeaderGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        leader.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LeaderBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        // TODO add your handling code here:
        if(passwordTF.getText().equals("password")){
            AdminGUI newGUI = null;
            try {
                newGUI = new AdminGUI();
            } catch (MalformedURLException ex) {
                Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            newGUI.setVisible(true);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null,"incorrect password");
        }
        
    }//GEN-LAST:event_adminBtnActionPerformed

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
         System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
        
    }//GEN-LAST:event_MinBMouseClicked

    private void StartBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("ButtonDefaultSecond.png"));
        StartBtn.setIcon(i);
        
    }//GEN-LAST:event_StartBtnMouseEntered

    private void StartBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMousePressed
        // TODO add your handling code here:
         ImageIcon i = new ImageIcon(getClass().getResource("ButtonDefaultThird.png"));
        StartBtn.setIcon(i);
    }//GEN-LAST:event_StartBtnMousePressed

    private void StartBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseReleased
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("ButtonDefault.png"));
        StartBtn.setIcon(i);
    }//GEN-LAST:event_StartBtnMouseReleased

    private void StartBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartBtnMouseExited
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("ButtonDefault.png"));
        StartBtn.setIcon(i);
    }//GEN-LAST:event_StartBtnMouseExited

    private void LeaderBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderBtnMouseEntered
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("ButtonleaderSecond.png"));
        LeaderBtn.setIcon(i);
    }//GEN-LAST:event_LeaderBtnMouseEntered

    private void LeaderBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderBtnMouseExited
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("Buttonleader.png"));
        LeaderBtn.setIcon(i);
    }//GEN-LAST:event_LeaderBtnMouseExited

    private void LeaderBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderBtnMousePressed
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("ButtonleaderThird.png"));
        LeaderBtn.setIcon(i);
    }//GEN-LAST:event_LeaderBtnMousePressed

    private void LeaderBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LeaderBtnMouseReleased
        // TODO add your handling code here:
        ImageIcon i = new ImageIcon(getClass().getResource("Buttonleader.png"));
        LeaderBtn.setIcon(i);
    }//GEN-LAST:event_LeaderBtnMouseReleased

    private void hideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideBtnActionPerformed
        // TODO add your handling code here:
        passwordTF.setVisible(true);
        adminBtn.setVisible(true);
    }//GEN-LAST:event_hideBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             
                
                try {
           
                    new StartGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(StartGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel IconLbl;
    private javax.swing.JButton LeaderBtn;
    private javax.swing.JLabel MinB;
    private javax.swing.JToggleButton SoundBtn;
    private javax.swing.JButton StartBtn;
    private javax.swing.JButton adminBtn;
    private javax.swing.JButton hideBtn;
    private javax.swing.JTextField passwordTF;
    // End of variables declaration//GEN-END:variables
}
