/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package continentalconquest;

import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ingrid Trant
 */
public class tempGUI extends javax.swing.JFrame {

    /**
     * Creates new form tempGUI
     */
    public tempGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        StartBtn2 = new javax.swing.JButton();
        TutorialBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        jLabel1.setText("If you are a new player, you should play the tutorial.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 150, 400, 40);

        StartBtn2.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        StartBtn2.setText("Start conquering now");
        StartBtn2.setBorderPainted(false);
        StartBtn2.setContentAreaFilled(false);
        StartBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartBtn2ActionPerformed(evt);
            }
        });
        getContentPane().add(StartBtn2);
        StartBtn2.setBounds(340, 270, 190, 80);

        TutorialBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        TutorialBtn.setText("Learn more first");
        TutorialBtn.setBorderPainted(false);
        TutorialBtn.setContentAreaFilled(false);
        TutorialBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TutorialBtnActionPerformed(evt);
            }
        });
        getContentPane().add(TutorialBtn);
        TutorialBtn.setBounds(70, 270, 190, 80);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartBtn2ActionPerformed
        // TODO add your handling code here:
        WorldMapGUI newGUI = null;
        try {
            newGUI = new WorldMapGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(SelectGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        newGUI.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_StartBtn2ActionPerformed

    private void TutorialBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TutorialBtnActionPerformed
        // TODO add your handling code here:
        EuropeTutorialGUI newGUI = new EuropeTutorialGUI();
        newGUI.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_TutorialBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tempGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tempGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tempGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tempGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tempGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JButton StartBtn2;
    private javax.swing.JButton TutorialBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
