package continentalconquest;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.geom.AffineTransform;
import java.awt.geom.Ellipse2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.image.BufferedImage;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x13332576
 */
public class WorldMapGUI extends javax.swing.JFrame {
    int score;
    BufferedImage image;
    JLabel label;
    /**
     * Creates new form WorldMap
     */
    public WorldMapGUI() throws MalformedURLException {
        initComponents();
        // CustomCursor();
        score = 0;
        jProgressBar1.setVisible(false);
          try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select * from player where p_sel = 'Y'";
            ResultSet rs = st.executeQuery(find);
            while(rs.next()){
                playerLbl.setText(rs.getString("name"));
                scoreLbl.setText(String.valueOf(rs.getInt("score")));
               
            }
            
            
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }   
        
    }
    
 public void CustomCursor() throws MalformedURLException
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(new URL("http://www.snazzyspace.com/cursorsfolder/sword.png"));
        Point point = new Point(0,0);
        Cursor cursor = toolkit.createCustomCursor(image, point,"Cursor");
        setCursor(cursor);
    }    
    
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asiaBtn = new javax.swing.JButton();
        ausBtn = new javax.swing.JButton();
        africaBtn = new javax.swing.JButton();
        amBtn = new javax.swing.JButton();
        europeBtn = new javax.swing.JButton();
        backgroundLbl = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        playerLbl = new javax.swing.JLabel();
        scoreLbl = new javax.swing.JLabel();
        Updatebtn = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MinB = new javax.swing.JLabel();
        CloseB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(620, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(620, 540));
        getContentPane().setLayout(null);

        asiaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        asiaBtn.setText("Asia");
        asiaBtn.setBorderPainted(false);
        asiaBtn.setContentAreaFilled(false);
        asiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asiaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(asiaBtn);
        asiaBtn.setBounds(470, 240, 180, 60);

        ausBtn.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        ausBtn.setText("Oceania");
        ausBtn.setBorderPainted(false);
        ausBtn.setContentAreaFilled(false);
        ausBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ausBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ausBtn);
        ausBtn.setBounds(450, 380, 180, 60);

        africaBtn.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        africaBtn.setText("Africa");
        africaBtn.setBorderPainted(false);
        africaBtn.setContentAreaFilled(false);
        africaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                africaBtnActionPerformed(evt);
            }
        });
        getContentPane().add(africaBtn);
        africaBtn.setBounds(280, 310, 160, 60);

        amBtn.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        amBtn.setText("America");
        amBtn.setBorderPainted(false);
        amBtn.setContentAreaFilled(false);
        amBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amBtnActionPerformed(evt);
            }
        });
        getContentPane().add(amBtn);
        amBtn.setBounds(100, 250, 160, 60);

        europeBtn.setFont(new java.awt.Font("Old English Text MT", 0, 36)); // NOI18N
        europeBtn.setText("Europe");
        europeBtn.setBorderPainted(false);
        europeBtn.setContentAreaFilled(false);
        europeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                europeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(europeBtn);
        europeBtn.setBounds(270, 190, 160, 60);

        backgroundLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/worldMap1.png"))); // NOI18N
        getContentPane().add(backgroundLbl);
        backgroundLbl.setBounds(0, 60, 620, 420);

        BackBtn.setFont(new java.awt.Font("Old English Text MT", 0, 18)); // NOI18N
        BackBtn.setText("Back ");
        BackBtn.setToolTipText("");
        BackBtn.setBorder(null);
        BackBtn.setBorderPainted(false);
        BackBtn.setContentAreaFilled(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(0, 30, 80, 30);

        jLabel1.setText("Current Player:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 50, 110, 14);
        getContentPane().add(playerLbl);
        playerLbl.setBounds(320, 50, 50, 14);

        scoreLbl.setToolTipText("");
        getContentPane().add(scoreLbl);
        scoreLbl.setBounds(430, 40, 70, 30);

        Updatebtn.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        Updatebtn.setText("Check your progress!");
        Updatebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdatebtnMouseClicked(evt);
            }
        });
        getContentPane().add(Updatebtn);
        Updatebtn.setBounds(220, 470, 200, 50);

        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(120, 480, 380, 30);

        jLabel3.setText("Score:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(390, 50, 50, 14);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/continentalconquest/OtherFrame.png"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 620, 540);

        MinB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinBMouseClicked(evt);
            }
        });
        getContentPane().add(MinB);
        MinB.setBounds(570, 0, 20, 20);

        CloseB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseBMouseClicked(evt);
            }
        });
        getContentPane().add(CloseB);
        CloseB.setBounds(600, 0, 20, 20);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void europeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_europeBtnActionPerformed
        // TODO add your handling code here:
     
                EuropeGUI newGUI= null;
        try {
            newGUI = new EuropeGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(WorldMapGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
                newGUI.setVisible(true);
                this.dispose();
          
    }//GEN-LAST:event_europeBtnActionPerformed

    private void ausBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ausBtnActionPerformed
        // TODO add your handling code here:
      
          try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select locked from continent where name = 'Australia' ";
            ResultSet rs = st.executeQuery(find);
           while(rs.next()){
            if(rs.getString("locked").equals("No")){
                OceaniaGUI newGUI = new OceaniaGUI();
                newGUI.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Conquer Europe to unlock this continent.");   
            }
           }
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }   
          
              
    }//GEN-LAST:event_ausBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
            try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=ZJuhRSgY0LY */
            String update = "update Player set p_sel = 'N';";
            st.executeUpdate(update);
            /* */


        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }  
        
        
        SelectGUI sel = null;
        try {
            sel = new SelectGUI();
        } catch (MalformedURLException ex) {
            Logger.getLogger(WorldMapGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        sel.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_BackBtnActionPerformed

    private void africaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_africaBtnActionPerformed
        // TODO add your handling code here:   
          try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select locked from continent where name = 'Australia' ";
            ResultSet rs = st.executeQuery(find);
           while(rs.next()){
            if(rs.getString("locked").equals("No")){
                AfricaQuizGUI newGUI = new AfricaQuizGUI();
                newGUI.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Conquer Europe to unlock this continent.");   
            }
           }
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }   
    }//GEN-LAST:event_africaBtnActionPerformed

    private void asiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asiaBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select locked from continent where name = 'Asia' ";
            ResultSet rs = st.executeQuery(find);
           while(rs.next()){
            if(rs.getString("locked").equals("No")){
                AsiaFrame newGUI = new AsiaFrame();
                newGUI.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Conquer Europe to unlock this continent.");   
            }
           }
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }          
    }//GEN-LAST:event_asiaBtnActionPerformed

    private void MinBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinBMouseClicked
        this.setState(StartGUI.ICONIFIED);
    }//GEN-LAST:event_MinBMouseClicked

    private void CloseBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseBMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CloseBMouseClicked

    private void amBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amBtnActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String connectionUrl = "jdbc:mysql://localhost:3307/jdbcTest?user=root&password=password";
            Connection conn = DriverManager.getConnection(connectionUrl);
            
            Statement st = (Statement) conn.createStatement();
            
            /* https://www.youtube.com/watch?v=MY4FavUyFNQ */
            String find = "select locked from continent where name = 'America' ";
            ResultSet rs = st.executeQuery(find);
           while(rs.next()){
            if(rs.getString("locked").equals("No")){
                AmericasGUI newGUI = new AmericasGUI();
                newGUI.setVisible(true);
                this.dispose();
            }
            else{
                JOptionPane.showMessageDialog(null,"Conquer Europe to unlock this continent.");   
            }
           }
        } catch (Exception ex) {
            System.out.println("AGGHHHH!!!!!");      
        }   
    }//GEN-LAST:event_amBtnActionPerformed

    private void UpdatebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdatebtnMouseClicked
        // TODO add your handling code here:
        jProgressBar1.setVisible(true);
        Updatebtn.setVisible(false);
        int value =Integer.parseInt(scoreLbl.getText());
        jProgressBar1.setValue(value);
    }//GEN-LAST:event_UpdatebtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws MalformedURLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorldMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorldMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorldMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorldMapGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
            WorldMapGUI app = new WorldMapGUI();
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new WorldMapGUI().setVisible(true);
                } catch (MalformedURLException ex) {
                    Logger.getLogger(WorldMapGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel CloseB;
    private javax.swing.JLabel MinB;
    private javax.swing.JLabel Updatebtn;
    private javax.swing.JButton africaBtn;
    private javax.swing.JButton amBtn;
    private javax.swing.JButton asiaBtn;
    private javax.swing.JButton ausBtn;
    private javax.swing.JLabel backgroundLbl;
    private javax.swing.JButton europeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel playerLbl;
    private javax.swing.JLabel scoreLbl;
    // End of variables declaration//GEN-END:variables
}
